### ISSUE TITLE
There is no Latte Palette

### ISSUE THREAD

**Issue by vinibispo** [catppuccin/tmux#10]
Hi, would it be nice to add a latte palette just like you have done on [nvim](https://github.com/catppuccin/nvim)

**Comment by vinnyA3** [comment]
Create pr for latte palette  (https://github.com/catppuccin/tmux/pull/11) -- check it out!  And let me know if there are some palette modifications that need to be made

**Comment by vinibispo** [comment]
Thanks @vinnyA3, it's perfect

**Comment by nekowinston** [comment]
I just merged #11, closing this. Thanks @vinnyA3!
