### ISSUE TITLE
Custom module update interval

### ISSUE THREAD

**Issue by lucky7xz** [catppuccin/tmux#101]
Hi. The .sh module below works fine, except that I cannot figure out how to have it update itself.

show_mem() {
  local index=$1

  local icon="$(get_tmux_option "@catppuccin_test_icon" "")"
  local color="$(get_tmux_option "@catppuccin_test_color" "$thm_blue")"
  var=$(free --giga | awk '/^Mem:/ {print $3 "/" $7 "/" $2 "GB"}')
  local text="$(get_tmux_option "@catppuccin_test_text" $var)"

  local module=$( build_status_module "$index" "$icon" "$color" "$text" )

  echo "$module"
}

![image](https://github.com/catppuccin/tmux/assets/59693852/1964d37f-d0c8-4598-8ce9-9da7f8005cbf)

I also have the battery module which is updated frequently. My guess is that custom modules work a little different in this regard. I appreciate your time. Thank you.

**Comment by peterkracik** [comment]
is there a way to refresh it when the window changes? 
I created a module to show the current branch, but it shows the same value for all windows

**Comment by 89iuv** [comment]
Currently you can not set a specific refresh interval per module.

The interval is set globally using:
```sh
set -g status-interval 1
```

Where "1" means 1 second.

**Comment by lucky7xz** [comment]
@89iuv 
> Currently you can not set a specific refresh interval per module.
> 
> The interval is set globally using:


-g status-interval was set to 2. The problem is that you can only get custom modules to update if you re-source the config. It does not update otherwise.

The question is : does re-sourcing include a routine that redrawing the status via interval does not (tried to figure it out but i'm still new to C)

OR

 var in my script is simply not updated when re-drawn. 

Thank you.

@peterkracik I believe you have the same problem. However, you could maybe try to re-source the conf when you switch windows via key-bindings. There's like a 0.3-0.5 delay when re-sourcing on my machine. Could you share it if you make it work? :)

**Comment by Myzel394** [comment]
> I am now trying to figure out how to pass the command directly into local text. Thank you.

@lucky7xz did you find a solution? I'm facing the same issue

**Comment by sgoudham** [comment]
Closing as original question seems to have been answered.
