### ISSUE TITLE
Current window icon cut off on right side

### ISSUE THREAD

**Issue by jkemp814** [catppuccin/tmux#102]
Hello everyone,

How do I lengthen the lower left side status bar. I'm using this theme without any mods, however the current folder icon is cut off.

![Screenshot from 2023-12-25 15-31-23](https://github.com/catppuccin/tmux/assets/12059343/dcb33d8e-c983-43e3-905f-2c786829d7e1)

**Comment by jkemp814** [comment]
It does that in both Gnome-Terminal and Alacritty. Using Bash or ZSH.

**Comment by 89iuv** [comment]
This looks to be an issue with the font that you are using. Can you try with Nerd font FiraCode and tell me if the issue is still there?

Font Link: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip
