### ISSUE TITLE
possibility to truncate the current working dir with `~` instead of /home/<username>

### ISSUE THREAD

**Issue by meuter** [catppuccin/tmux#107]
Hi,

Would it be possible to adapt the directory module to have an option that would truncate the cwd to use `~/` instead of `/home/<username>`. I am working in and Android Open Source Project (AOSP) and the paths there are already quite long. The status bar is pretty crowded so getting back a dozen or so characters would be precious.

If you point me in the right direction, I would be willing to constribute a PR.

Thanks in advance for considering this feature request.

Kind regards

EDIT: typo

**Comment by 89iuv** [comment]
You can use this in your .tmux.com

```sh
set -g @catppuccin_window_current_text "#( echo \#{pane_current_path} | sed \"s|$HOME|~|\" )"
set -g @catppuccin_window_default_text "#( echo \#{pane_current_path} | sed \"s|$HOME|~|\" | xargs basename )"
```

This will replace you "/home/username" with "~" and for the current window it will display the full path, and for the default window it will display only the folder.

**Comment by meuter** [comment]
Thanks for the response! Based on your suggestion I ended up with this which does the job perfectly:
```
set -g @catppuccin_directory_text "#( echo \#{pane_current_path} | sed \"s|$HOME|~|\" )"
```
