### ISSUE TITLE
Window default fill overrides current fill for middle separator

### ISSUE THREAD

**Issue by minescoviciu** [catppuccin/tmux#108]
Config:
```
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " █"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_fill "all"
```
I would have expected to have the same color for the current window not a blank space.
<img width="343" alt="image" src="https://github.com/catppuccin/tmux/assets/17749202/d3988d1d-c291-46bd-ba9a-952912d48362">

**Comment by 89iuv** [comment]
This is a hard issue to fix because it may break the other configs.

I think that the theme should fallow the same pattern for defining the elements of the window, as it does for the module. 
This implies a big rework of the current window implementation.
