### ISSUE TITLE
The `#[bg=default]` does not work properly(?)

### ISSUE THREAD

**Issue by Dolfost** [catppuccin/tmux#109]
I am trying to set the `@catppuccin_battery_text` to  `"#{battery_color_charge_fg}#{battery_percentage}"`
Result is:
![Screenshot 2024-01-07 at 4 55 27 PM](https://github.com/catppuccin/tmux/assets/59747489/2beb433d-defd-4bb7-9cde-63c9fac7c41c)
(notice the background of 100%)

So, to make it the default one I do
```
set -g @catppuccin_battery_text "#{battery_color_charge_fg}#[bg=default]#{battery_percentage}"
```
But  I get the same result. How to get the status line background color?

**Comment by 89iuv** [comment]
You could try:
```sh
set -g @catppuccin_battery_text "#[fg=#{battery_color_charge_fg}]#{battery_percentage}"
```

This should set the foreground color to #{battery_color_charge_fg} for #{battery_percentage}
My assumption here is that #{battery_color_charge_fg} contains the value for the color of the text.

**Comment by Dolfost** [comment]
> You could try:
> 
> ```shell
> set -g @catppuccin_battery_text "#[fg=#{battery_color_charge_fg}]#{battery_percentage}"
> ```
> 
> This should set the foreground color to #{battery_color_charge_fg} for #{battery_percentage} My assumption here is that #{battery_color_charge_fg} contains the value for the color of the text.

This is what I get with this setup (no green charged color for text and extra bracket):

![Screenshot 2024-03-24 at 1 28 47 PM](https://github.com/catppuccin/tmux/assets/59747489/c2fc0da5-0bbf-4597-9ee5-1492c1255042)

**Comment by 89iuv** [comment]
Can you please give more information on what you want to accomplish?

**Comment by Dolfost** [comment]
> `@catppuccin_battery_text` to `"#{battery_color_charge_fg}#{battery_percentage}"`

I want to set `@catppuccin_battery_text` to `"#{battery_color_charge_fg}#{battery_percentage}"` so the battery percentage foreground will change based on my battery percentage. When I do it, the background is also changed for some reason and this look awful.

**Comment by vdbe** [comment]
`set -g @catppuccin_battery_text "#{battery_color_charge_fg}#[bg=#{thm_gray}]#{battery_percentage}"` this should work.
Depending on your `@catppuccin_status_fill` the value for bg can change:
- icon (default): `#{thm_gray}`
- all: `#{thm_yellow}`

**Comment by vdbe** [comment]
`#{thm_gray}` syntax was only merged a couple days ago have you updated the plugin?

```bash
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha
set -g @catppuccin_window_status_icon_enable "yes"
set -g @catppuccin_icon_window_last "<U+F05B0>"
set -g @catppuccin_icon_window_current "<U+F05AF>"
set -g @catppuccin_icon_window_zoom "<U+F004C>"
set -g @catppuccin_icon_window_mark "<U+F00C0>"
set -g @catppuccin_icon_window_silent "<U+F009B>"
set -g @catppuccin_icon_window_activity "<U+F05B2>"
set -g @catppuccin_icon_window_bell "<U+F009E>"
set -g @catppuccin_date_time_text "%a %h %d %H:%M"
#  TODO: fix #{battery_percentage} background text
# set -g @catppuccin_battery_text "#{battery_color_charge_fg}#[bg=default]#{battery_percentage}" # original
# set -g @catppuccin_battery_text "#[fg=#{battery_color_charge_fg}]#{battery_percentage}" # tired too
# set -g @catppuccin_battery_text "#{battery_color_charge_fg}#[bg=#{thm_gray}]#{battery_percentage}" # wont work either
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "session battery date_time"
set -g @catppuccin_status_modules_left "user"

# Added this line
set -g @catppuccin_battery_text "#{battery_color_charge_fg}#[bg=#{thm_gray}]#{battery_percentage}"

set -g @batt_remain_short 'true'
set -g @batt_icon_status_charged ' '
set -g @batt_icon_status_charging ' ↑'
set -g @batt_icon_status_discharging ' ↓'
set -g @batt_icon_status_attached ' ⚠ '
set -g @batt_icon_status_unknown ' ?'
set -g @batt_color_status_primary_charged colour2
set -g @batt_color_status_primary_charging colour83
set -g @batt_color_status_primary_attached colour1
set -g @batt_color_status_primary_unknown colour227
set -g @batt_color_status_primary_discharging colour5
```
![image](https://github.com/catppuccin/tmux/assets/44153531/ad8ec996-9871-4f2c-8035-3f23df24529f)
![image](https://github.com/catppuccin/tmux/assets/44153531/e4e89fab-adc9-4091-a249-89e39ed862d5)

**Comment by Dolfost** [comment]
> have you updated the plugin?

No, I did not when were testing it. I updated everything and tried again, it works as I wanted it to. Thank You a lot!
