### ISSUE TITLE
Setting only a one of the window_status properties

### ISSUE THREAD

**Issue by varunkas** [catppuccin/tmux#116]
Hi, I would like to only show the "@catppuccin_icon_window_zoom" icon. But currently, when I use `set -g @catppuccin_window_status_enable "yes"`, all the other status icons also appear. Is there a way to disable this behaviour? I tried setting the others to an empty string like this: `set -g @catppuccin_icon_window_last ""`, but it does not seem to work. Any suggestions? Thanks so much!

**Comment by 89iuv** [comment]
The configuration is all icons or no icon. There is no option to show only the window zoom icon as of now.

**Comment by dsincl12** [comment]
I haven't tried this but can you just assign null to the icons you "don't want"? I want to have the same option as @varunkas as well.

**Comment by varunkas** [comment]
@dsincl12 I have only tried setting empty string, ie. "" or a space " ". The empty string doesn't do anything. And the space just looks weird.

**Comment by dsincl12** [comment]
ok I'll try with "null" since that's how you remove other icons. I will report back :)

**Comment by varunkas** [comment]
Ah, that's good to know. Please update! I'll also give it a go later today. Thanks!

**Comment by varunkas** [comment]
I'm happy to let you know that this worked, Thanks @dsincl12! Here is my configuration for this aspect:

```
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"
set -g @catppuccin_icon_window_zoom ""
set -g @catppuccin_icon_window_last "null"
set -g @catppuccin_icon_window_current "null"
set -g @catppuccin_icon_window_mark "null"
set -g @catppuccin_icon_window_silent "null"
set -g @catppuccin_icon_window_activity "null"
set -g @catppuccin_icon_window_bell "null"
```

**Comment by dsincl12** [comment]
Awesome! I never got around to it today unfortunately. Thank you for posting the config, much appreciated @varunkas!

**Comment by sgoudham** [comment]
Closing as original question has been answered / configuration is present.

@89iuv - Is it worth adding some information how to disable window icons in the README?
