### ISSUE TITLE
How to remove the status bar icons on the right?

### ISSUE THREAD

**Issue by adrian-montero-hkkd** [catppuccin/tmux#118]
I installed the catppuccin theme for tmux, I love it, but I want to remove the icons on the right with my battery/AC percent, network name, temp and location.
![image](https://github.com/catppuccin/tmux/assets/145811752/f961b923-9083-46b9-9eb6-5cb3cecda688)

I already tried all of these and they keep appearing? Is it possible to remove that?
```
set -g @catppuccin_status_modules_right "..."
set -g @catppuccin_status_modules_left "..."
set -g status-right ""
set -g status-left "..."
```

**Comment by vdbe** [comment]
The icons are removed on a per module basis

```
# set -g @catppuccin_[module_name]_icon ""
set -g @catppuccin_battery_icon ""
set -g @catppuccin_weather_icon ""
# ...
```
[override-the-specific-module-icon](https://github.com/catppuccin/tmux/blob/aa12d6f0ef74718868a645da8e5cd4773e369a97/README.md#override-the-specific-module-icon)

Would be handy if `status_fill` had an extra variant for no icons, currently it does not.

**Comment by 89iuv** [comment]
@adrian-montero-hkkd did the comment from @vdbe helped you with this issue?
