### ISSUE TITLE
Follow system theme?

### ISSUE THREAD

**Issue by eulersson** [catppuccin/tmux#119]
Is there a way to be able to make catpuccin follow the system's theme?

I saw this user that I guess wanted to do it https://github.com/catppuccin/tmux/issues/83 

There's a user that wrote a tmux plugin that would use [dark-notify (macOS)](https://github.com/cormacrelf/dark-notify) to detect when the system preference changes and would update the a symlink to a theme that .tmux.conf reads from and then would re-source the .tmux.conf again, but it seems catpuccin is not as simple.

It would be very nice to have a theme hot-swap in catpuccin's tmux flavor (`set -g @catppuccin_flavour 'latte'` for light and moccha for dark).

Thanks for the super great themes and organization 🙏

**Comment by 89iuv** [comment]
While the idea seems interesting, this is out of scope for now.

The plugin you mentioned looks to do exactly what you are asking.
