### ISSUE TITLE
ITerm2 not displaying the status bar properly

### ISSUE THREAD

**Issue by Seth-the-cat** [catppuccin/tmux#122]
I have been trying to fix this for a good 6 hours combined, and I can't find anything that works.
My .tmux.conf is [tmux.txt](https://github.com/catppuccin/tmux/files/14057873/tmux.txt)
Here is a screenshot of the status bar
![Screenshot 2024-01-25 at 15 17 46](https://github.com/catppuccin/tmux/assets/71609066/e719ff69-2932-49de-9498-699782cd5652)

I'm on 3.3a Tmux

**Comment by Seth-the-cat** [comment]
I broke it so much I have given up as the nerd font I was using is getting overwritten somewhere so in tmux there is no nerd font and its all broken

**Comment by Seth-the-cat** [comment]
I deleted and am back to the point where the font works, but the colors are still messed up

**Comment by sgoudham** [comment]
Hey :wave: @Seth-the-cat 

I'm unable to open your `tmux.txt` for some reason, I'd appreciate if you could paste your configuration in a code block. Also, can you provide more detailed information on what you've tried to fix this?

Thanks!

**Comment by richardfaulkner-qz** [comment]
I ran into a similar issue. I was able to get the icons fixed by installing nerd fonts. [This video](https://www.youtube.com/watch?v=mQdB_kHyZn8) may help you with that.

**Comment by Seth-the-cat** [comment]
> I ran into a similar issue. I was able to get the icons fixed by installing nerd fonts. [This video](https://www.youtube.com/watch?v=mQdB_kHyZn8) may help you with that.

I have nerd font installed.
![Screenshot 2024-03-18 at 23 36 04](https://github.com/catppuccin/tmux/assets/71609066/eb2cd61e-d950-42fa-9a06-0e5b0ab939f9)
powerline-10k uses nerd fonts also and that's working fine.

> Hey 👋 @Seth-the-cat
> 
> I'm unable to open your `tmux.txt` for some reason, I'd appreciate if you could paste your configuration in a code block. Also, can you provide more detailed information on what you've tried to fix this?
> 
> Thanks!

Here is the tumx.conf file.
[tmux.txt](https://github.com/catppuccin/tmux/files/14645352/tmux.txt)
Note, the .tmux.reset.conf reference is only key binds for tmux.

I have reinstalled the nerd fonts a couple of times. I also changed the text settings in Iterm. Changing the "ambiguous characters are double width" and "Unicode normalization form" (I don't know what that does exactly) none of these fixed anything. I reinstalled the catppuccin plugin multiple times. Nothing changed.

I have noticed when I reload the battery and CPU show up for a second then disappear.
https://github.com/catppuccin/tmux/assets/71609066/77a1d12d-ce2e-467c-82c9-c983bab45393

One last thing is that I have found that at some point I had to start using `tmux -u` to start because the font wouldn’t carry over.

I'm sorry I couldn’t respond faster, I have been busy.

**Comment by 89iuv** [comment]
Hi @Seth-the-cat 

By looking at your tmxu config and the output it looks like tmux is doing what it was instructed and this is not a font issue.
It also seems that some plugins do not work and because of that you get a lot of diferent color separators on the right.

In order to fix this i would do the the fallowing:

1. Start with an example config: https://github.com/catppuccin/tmux?tab=readme-ov-file#config-3
2. Add plugins one at a time and make sure that they work and look as expected
3. Customize tmux catppuccin to your preference
