### ISSUE TITLE
Slow updates when showing directory or application

### ISSUE THREAD

**Issue by chyld** [catppuccin/tmux#125]
Updates are slow when using either the application or directory module.

So, if I change my directory or if I launch a new process, these changes will get reflected in tmux, however it can take up to 10 seconds for the changes to appear.

Is there a setting I can set to make this more instantaneous?

**Comment by 89iuv** [comment]
You could try to set the interval for tmux update to 1 second: 
```sh
set -g status-interval 1
```

The default is 15 seconds.

**Comment by 89iuv** [comment]
Closing this one as there had been more than 2 weeks without reply from the author.
