### ISSUE TITLE
Little Error In README.md

### ISSUE THREAD

**Issue by IsaacTheKind** [catppuccin/tmux#131]
Hey there,

I think there is a small error in `README.md`. I was using one of the example configs, and it took me a while to understand why no matter what I did, the modules on the right would not accurately reflect what was specified in the config. I thought I would leave an issue so others don't have the same trouble. Eventually I realized the issue was that I need to use this:

`set -g @catppuccin_status_modules "application session user host date_time"`

But all the examples in `README.md` use this:

`set -g @catppuccin_status_modules_right "application session user host date_time"`

Awesome repo, thank you for making this!

**Comment by vdbe** [comment]
`catppuccin_status_modules` has indeed been renamed to `catppuccin_status_modules_right` in #71.

I think you are referring to this line
https://github.com/catppuccin/tmux/blob/a0119d25283ba2b18287447c1f86720a255fb652/custom/README.md?plain=1#L16

Feel free to open a pull request update it.
