### ISSUE TITLE
How to change status bar color?

### ISSUE THREAD

**Issue by LaurensDSchunk** [catppuccin/tmux#134]
## Issue
The tmux status bar is not updating its color. I want it to look like it does in this repo's images. I am using alacritty as my terminal. Perhaps just a way to change the color of the status bar?

## Screenshot
<img width="798" alt="Screenshot 2024-02-15 at 8 06 25 AM" src="https://github.com/catppuccin/tmux/assets/101758235/936643e8-9995-42fa-b9ce-32a754228399">

## Desired Effect (Darkest status bar)

<img width="100" alt="Screenshot 2024-02-16 at 11 46 10 AM" src="https://github.com/catppuccin/tmux/assets/101758235/eb6a016d-a24e-4fb0-be08-72faf662eee4">

## .tmux.conf
```
bind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set-option -g remain-on-exit on

set -sg escape-time 10
set-option -g status-position top
set -g mouse on

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Fix Colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @catppuccin_flavour 'mocha' # latte or frappe, macchiato, mocha

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
```

**Comment by LaurensDSchunk** [comment]
I would like an effect similar to that on the far right of this image. How would I accomplish this?

<img width="578" alt="Screenshot 2024-02-16 at 11 41 42 AM" src="https://github.com/catppuccin/tmux/assets/101758235/8ec70442-10ac-439d-bd53-be48a6a19302">

**Comment by CrazyCatZhang** [comment]
`set -g status-bg "#191724"
`

**Comment by phanorcoll** [comment]
is it possible to make the status bar bg transparent, only leave the color for the sections?  if so, can you provide an example. Thanks

**Comment by CrazyCatZhang** [comment]
> is it possible to make the status bar bg transparent, only leave the color for the sections?  if so, can you provide an example. Thanks

You can achieve a transparent effect by setting the background color to match the background color of your terminal.

or `set -g status-bg default`

**Comment by sgoudham** [comment]
Hey :wave: @LaurensDSchunk 

Does the following line answer your question?

> set -g status-bg "#191724"
>
> @CrazyCatZhang

**Comment by ferrarafer** [comment]
I also cannot change the status bar color but I don't know if I am doing something wrong.

My terminal has a transparent background and I want the status bar of tmux to mimic that.

<img width="1498" alt="Screenshot 2024-03-18 at 12 07 20 AM" src="https://github.com/catppuccin/tmux/assets/1505545/fe029a57-ba15-40e1-84d0-f06479168047">

**Comment by abeerance** [comment]
The easiert way to adjust it, is to define a catppuccin flavour and adjust the thm_bg of said flavour. This will adjust the color of the status bar properly:
![CleanShot 2024-03-18 at 5  26 47](https://github.com/catppuccin/tmux/assets/64221366/e3c355f5-bd5a-4754-b4b9-194aaab53431)

I am unsure though if transparency is possible, since the transparency is being handled by your chosen terminal and not by tmux itself @ferrarafer .

**Comment by MaarcusRenieroL** [comment]
> The easiest way to adjust it is to define a catppuccin flavour and adjust the thm_bg of said flavour. This will adjust the color of the status bar properly: ![CleanShot 2024-03-18 at 5  40 36](https://private-user-images.githubusercontent.com/64221366/313764021-30a435be-a556-4d76-9ca5-8f8b25003714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjI5MjAsIm5iZiI6MTcxMTU2MjYyMCwicGF0aCI6Ii82NDIyMTM2Ni8zMTM3NjQwMjEtMzBhNDM1YmUtYTU1Ni00ZDc2LTljYTUtOGY4YjI1MDAzNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE4MDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNWMwMTViYTkxNTczMzIzODBiZjQ2MjllOGY5NGIzZmFkYmU1YWFmNWQ2MDQxZThiMWRiZDM4NGI1MzgxYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zfeAXotMftfxhA2vxES8VlakOhtFl2_u0EU0xDJLySk) I am unsure though if transparency is possible, since the transparency is being handled by your chosen terminal and not by tmux itself @ferrarafer . I did try achieve a certain transparency with iterm2, but I wasn't able to achieve a preferred amount of continual transparency.

This solution helped me. And yes it's a simple one

**Comment by 89iuv** [comment]
There is a new experimental option added for this: https://github.com/catppuccin/tmux?tab=readme-ov-file#override-the-default-status-background-color

In iterm2 i can make the terminal transparent, including the tmux status bar:
<img width="1494" alt="Screenshot 2024-03-27 at 20 19 26" src="https://github.com/catppuccin/tmux/assets/3298487/d494b458-9ef9-4e23-9ca1-df97ae80c473">

**Comment by ferrarafer** [comment]
Hi @89iuv, can you share your config please?

**Comment by 89iuv** [comment]
@ferrarafer here is my tmux config from my .dotfiles. I do change it once in a while so it may not look like the image above.
