### ISSUE TITLE
catppuccin_window_current_text = window name?

### ISSUE THREAD

**Issue by tomaszstachera** [catppuccin/tmux#135]
Is there an option to set window name to be shown instead of directory or application? LIke in plain tmux.

**Comment by karismatic-megafauna** [comment]
I am also looking for this option! I like using `tmuxinator` to create and name my windows and not having this ability breaks that functionality for me

**Comment by karismatic-megafauna** [comment]
Actually, this is possible via these configs!

 via https://github.com/catppuccin/tmux/issues/53#issuecomment-1675211611

Just tested and works for me ❤️

**Comment by tomaszstachera** [comment]
> Actually, this is possible via these configs!
> 
> via [#53 (comment)](https://github.com/catppuccin/tmux/issues/53#issuecomment-1675211611)
> 
> Just tested and works for me ❤️

Excellent :) I am closing this one.
