### ISSUE TITLE
How to customize colors for the session module?

### ISSUE THREAD

**Issue by Myzel394** [catppuccin/tmux#140]
I'm currently trying to change the colors for the session module to create a monochromatic theme.

I tried the following code:

```tmux
set -g @catppuccin_window_default_color "#3b3f56" # text color
set -g @catppuccin_window_default_background "#1c1e28"

set -g @catppuccin_window_current_color "#656c92" # text color
set -g @catppuccin_window_current_background "#464b65"

set -g @catppuccin_application_color "#505674"
set -g @catppuccin_session_color "#656c92"
```

This does work fine, however the color won't change when I press `prefix`.

[I found out that the session module uses `$thm_red,$thm_green` to get the current color](https://github.com/catppuccin/tmux/blob/main/status/session.sh). I guess chaning `$thm_red` or `$thm_green` could result in unwanted consequences, is there some other way to modify the active color in a different way? If not, how do I change those variables?

**Comment by vdbe** [comment]
The default for `catppuccin_session_color` is `#{?client_prefix,$thm_red,$thm_green}` not a single color.
`set -g @catppuccin_session_color "#{?client_prefix,#656c92,<other color>}"` should do the trick.

**Comment by Myzel394** [comment]
Oh well actually easier than expected, thanks!

**Comment by linkarzu** [comment]
Wonderful, thank you very much @vdbe
