### ISSUE TITLE
Tmux window indicator rendering issue with FiraCode Nerd font in Windows Terminal

### ISSUE THREAD

**Issue by TheNemoNemesis** [catppuccin/tmux#147]
### Description:
I've been using the catppuccin theme for tmux in combination with the FiraCode Nerd font on Windows Terminal within WSL. However, recently I encountered a rendering issue with the tmux window indicator. Specifically, there seems to be a disconnect between the separator and the window number, resulting in a column of pixels between them.

### Steps to Reproduce:
1. Set up Windows Terminal with WSL.
2. Use the catppuccin theme for tmux.
3. Set the font to "FiraCode Nerd".
4. Open multiple tmux windows.

### Expected Behavior:
The tmux window indicator should render correctly with no visual artifacts, and there should be no disconnect between the separator and the window number.

### Actual Behavior:
There is a noticeable disconnect between the separator and the window number, resulting in a visual artifact.

### Additional Information:
- This issue appeared suddenly without any changes to my configuration.
- I've tried troubleshooting by adjusting font sizes, checking for updates, and reviewing configuration settings, but the issue persists.
- Changing fonts did not resolve the issue, indicating it may not be specific to the FiraCode Nerd font.
- Screenshots of the issue are attached for reference.

### Environment:
- **Operating System:** Windows with WSL
- **Terminal Emulator:** Windows Terminal
- **tmux Version:** Tmux 3.4
- **catppuccin Version:** Updated to the last available using tpm
- **Font:** FiraCode Nerd

### Screenshots:
![Screenshot 2024-02-25 213547](https://github.com/catppuccin/tmux/assets/140025279/67876b7f-2b91-4263-99fb-3b2bb8c0c016)
![Screenshot 2024-02-29 233143](https://github.com/catppuccin/tmux/assets/140025279/3e78b951-64fb-4886-ac7d-aba968d5fdee)
![Screenshot 2024-02-29 233143arrow](https://github.com/catppuccin/tmux/assets/140025279/aad815bd-96bb-4e14-80f6-ddc666b425f0)

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you!

**Comment by shadow-absorber** [comment]
have the same problem in alacritty( terminal emulator ) on endeavour os( linux ) with the mononoki nerd font

**Comment by shadow-absorber** [comment]
![image](https://github.com/catppuccin/tmux/assets/10175699/72ede07d-d171-422d-9a8d-73e973d9b445)

**Comment by shadow-absorber** [comment]
here is a better pictures: 
![image](https://github.com/catppuccin/tmux/assets/10175699/f12fa093-cdf2-49ce-be6a-7482be5a29be)

![image](https://github.com/catppuccin/tmux/assets/10175699/ec3a0cd0-0121-4498-a5a6-c3c6dda26bcf)

**Comment by 89iuv** [comment]
This is a common issue with the way some terminals render fonts.
A detailed explanation can be found here: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#sub-pixel-imperfections-around-powerline-symbols

What you could try:

- try a different terminal emulator
- try a different font
- increase or decrease the font size

Other than that there is nothing inside of tmux that can be done to address this issue.

**Comment by shadow-absorber** [comment]
or disable sub-pixel anti aliasing fontconfig on linux also fixes the issue if you are fine with that
