### ISSUE TITLE
weather module not displayed properly

### ISSUE THREAD

**Issue by qrockz** [catppuccin/tmux#150]
```
flatpak run org.wezfurlong.wezterm --version
wezterm 20240203-110809-5046fc22
```
![weather](https://github.com/catppuccin/tmux/assets/56853194/99750b7b-79f5-438b-9da1-4b52347813b0)

```
gnome-terminal --version
# GNOME Terminal 3.51.0 using VTE 0.75.0 +BIDI +GNUTLS +ICU +SIXEL +SYSTEMD
```
![weather2](https://github.com/catppuccin/tmux/assets/56853194/d4dcd6e5-b2db-4a07-b2fe-e0c9529f3986)
In both terminals a black seperator is shown in the weather module and for the gnome-terminal the cloud icon is not displayed.
```
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_status_modules_right "directory date_time weather"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @plugin 'xamut/tmux-weather'
set-option -g @tmux-weather-location "Dresden"
set-option -g @tmux-weather-interval 1
```

**Comment by vdbe** [comment]
Can't replicate the issue but it looks like the black block is part of `#{weather}` (xamut/tmux-weather output).
Do you also have it with `set-option -g status-right "#{weather}"` (excluding catppuccin/tmux from the equation)?

Maybe you can solve it by changing `@tmux-weather-format`.

**Comment by qrockz** [comment]
Do you also have it with set-option -g status-right "#{weather}" (excluding catppuccin/tmux from the equation)?

> Can't replicate the issue but it looks like the black block is part of `#{weather}` (xamut/tmux-weather output). Do you also have it with `set-option -g status-right "#{weather}"` (excluding catppuccin/tmux from the equation)?
> 
> Maybe you can solve it by changing `@tmux-weather-format`.

When disabling cattpuccin and use `set-option -g status-right "#{weather}"` the icon is displayed correctly without a black block. 
The black block only appears on this specific cloud icon so far. When another cloud icon is displayed (e.g. cloud with sun) then there is no black block and all is fine.

Theese display issues only happen in tmux with cattpuccin. Running the _wttr_ script in the terminal works always fine.

**Comment by qrockz** [comment]
I've edited the `../plugins/tmux-weather/scripts/weather.sh` and give the weather plugin a fixed string:
`$(set_tmux_option "@weather-previous-value" "☁️ wtf")`

![weather](https://github.com/catppuccin/tmux/assets/56853194/8465c332-98dd-493c-b3d9-97275f45087b)

**Comment by vdbe** [comment]
If you are not using a nerd font try that, but I don't think it's a problem with this plugin.

**Comment by qrockz** [comment]
> If you are not using a nerd font try that, but I don't think it's a problem with this plugin.
I'm using nerd font. Yeah, it's not a cattpuccin issue.
