### ISSUE TITLE
Looking For More Maintainers!

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/tmux#155]
Hi :wave:
I'm one of the core maintainers for Catppuccin, who has oversight over the entire organisation.

Our current tmux maintainer, @89iuv, has done some amazing work in refactoring and improving the functionality of the plugin in recent months (Thank you!) However, they are no longer able to dedicate the same amount of time to maintaining the plugin so I'm putting out a request for more maintainers.

I'd be looking for someone who:

- Uses (and cares about!) the plugin
- Can answer questions raised via issues
- Can review/merge PRs to improve functionality, fix bugs, etc.
- Enjoys all the other cool stuff that comes with maintaining a repository :D 

I'll be available to do light issue/PR triaging on this repository but I can only do so much without being a tmux user myself :sweat_smile: 
 
Please reply to this issue if you are interested!

**Comment by vdbe** [comment]
:hand:

**Comment by sgoudham** [comment]
Thanks for volunteering @vdbe, I've also seen you helping out in issues and PRs so cheers for that!

I'll leave this issue open for a few more days in case we have some other people that are interested too.
