### ISSUE TITLE
Use window titles for tabs instead of directory names

### ISSUE THREAD

**Issue by RobertMenke** [catppuccin/tmux#16]
Hey, it's pretty common to use multiple tmux windows in the same directory. Currently, this config uses the name of the working directory to describe the tab and only shows the window title in a tab on the right. It seems like this should be the inverse, with the window titles describing the tabs and the directory name shown on the right.

Example from a project I'm working on:
<img width="1136" alt="CleanShot 2022-10-02 at 15 25 20@2x" src="https://user-images.githubusercontent.com/13398229/193472482-94c1834c-f5b7-4462-b871-5cec787de6dd.png">

Thank you for putting this config together!

**Comment by nekowinston** [comment]
That makes sense, I'll give it a try this week.

**Comment by RobertMenke** [comment]
Wonderful, thank you!!

**Comment by andreasgrafen** [comment]
On a further note: Is this something that can be decoupled from the colour scheme and put into the users responsibility to configure to their liking?

**Comment by nekowinston** [comment]
I merged the PR for TPM support (#2), so now we have options available in the theme:

https://github.com/catppuccin/tmux/blob/bd1ea4b86a159faddbb049e6be8082217348234d/catppuccin.tmux#L19

I think this issue is absolutely worth having an option for, especially if people get the preset from TPM.

**Comment by andreasgrafen** [comment]
Agreed. With things like this, that are something that every user might want to handle differently, we should give a choice. c:

**Comment by sdemura** [comment]
I've been using this fork, which does exactly this: https://github.com/rwxd/catppuccin-tmux

**Comment by rogeruiz** [comment]
@RobertMenke I agree with @andreasgrafen on this. I think the best approach here is to do this kind of work in waves. I'm curious to hear some feedback on this question.

- Is your current issue here that you want to flip the folders to the right hand side and the windows to the left hand side? If so that's a good place to start with customizing things.

Also, I have some pretty ambitious ideas here to allow anyone to run any arbitrary command on either side of the line including the middle if they want by adding calls to custom scripts that you maintain yourself.

**Comment by RobertMenke** [comment]
@rogeruiz Exactly! Cool idea on arbitrary customization I’d just make sure that it’s documented to use caution running 3rd party code there for newcomers ;).

**Comment by rogeruiz** [comment]
Alright, #22 should close this when it's merged into the default branch. If anyone would like to test this out, you _should_ be able to set a new remote to my GH fork and then change branches to `add-option-to-display-folders`.

The commands to do that in your local Git repository should be:

```sh
cd ~/.tmux/plugins/tmux
git remote add rogeruiz https://github.com/rogeruiz/tmux.git
git fetch --all
git checkout add-option-to-display-folders
```

Afterwards, you can follow the documentation in the `README.md` to turn on the feature. Remember to source your Tmux configuration file when you update it if you're in a session.

When you're done, you can remove the remote and go back to the default branch with the following:

```sh
cd ~/.tmux/plugins/tmux
git remote rm rogeruiz
```

**Comment by RobertMenke** [comment]
@nekowinston Does @rogeruiz 's PR adequately address this issue from your point of view?
