### ISSUE TITLE
Getting this to work in alacritty terminal under archlinux...

### ISSUE THREAD

**Issue by mrgreen3** [catppuccin/tmux#166]
Have got TPM installed and it runs, added line to run catppuccin from .tmux.conf but I only get a white bar with coloured blocks. Am assuming I need to load a nerd font. 

Would very much like a dark theme as I have seen this in screenshots and it looks beautiful.

My .tmux.conf is as follows

``
unbind r
bind r source-file /home/mrgreen/.tmux.conf

set -g prefix C-s

set -g mouse on

set-option -g status-position top

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'

``

**Comment by vdbe** [comment]
Yes you need a nerd font, with the config provided it should look something like this
![image](https://github.com/catppuccin/tmux/assets/44153531/6566a66d-2c6c-4ef9-b073-f6ae0f096e7c)

**Comment by mrgreen3** [comment]
Yes please ;-)...... beautiful

**Comment by vdbe** [comment]
Does it work with nerd fonts? If not can you provide a screenshot?

**Comment by mrgreen3** [comment]
It kind of does but does not look like yours at all, know I have awesome fonts loaded [for i3blocks]

![2024-03-17-105844_1920x1080_scrot](https://github.com/catppuccin/tmux/assets/51655601/146502b3-cc55-477e-b9dc-92561d8946f3)

**Comment by mrgreen3** [comment]
Right so I have a path issue, reloading config tmux is looking in .tmux.conf rather than ~/.config/tmux/tmux.conf...

**Comment by mrgreen3** [comment]
Ok so I have now got paths correct and working, oading plugins works...do need to figure font package and configuration but I now have this...

![2024-03-17-111244_1920x1080_scrot](https://github.com/catppuccin/tmux/assets/51655601/dc10c301-87fc-4760-8f3b-91419443c3d4)

**Comment by vdbe** [comment]
You still need a nerd font

**Comment by mrgreen3** [comment]
![2024-03-17-112325_1920x1080_scrot](https://github.com/catppuccin/tmux/assets/51655601/c6663c15-581d-4852-9d11-15bebe2c487a)

Getting there...

**Comment by vdbe** [comment]
That is 100% correct (my screenshot still had some @catppuccin_ options set)

**Comment by mrgreen3** [comment]
Was following this:

https://www.youtube.com/watch?v=jaI3Hcw-ZaA

Thank you for your help, off to configure alacritty now ;-)
