### ISSUE TITLE
zoom indicator

### ISSUE THREAD

**Issue by sdemura** [catppuccin/tmux#17]
It would be nice to have a zoom indicator. Vanilla tmux does this by adding 'Z' to the window name.

**Comment by rogeruiz** [comment]
Hey @sdemura this is coming in a new version of the plugin. Stay tuned. I have one question to ask though.

- Is it okay that this is supported with a Nerdfont variable? Would you expect to see a `Z` character and have to enable the `@catppuccin-nerd-fonts` option in the configuration?

Thanks!

**Comment by rogeruiz** [comment]
Hi @sdemura. 👋🏽  You should be able to test out the branch in #24 locally and let me know what you think. I don't have documentation ready for it. But if you checkout that branch locally and run it, the window status is supported automatically. And you can toggle on nerd fonts support by adding the following to your Tmux configuration.

```conf
set -g @catppuccin_window_icons_enabled on
```

Take it for a test and let me know what you think by commenting over in the PR. (#24). thanks!

**Comment by 89iuv** [comment]
Implemented in https://github.com/catppuccin/tmux/pull/57
