### ISSUE TITLE
Is there anyway to make the background line transparent?

### ISSUE THREAD

**Issue by shalawfatah** [catppuccin/tmux#176]
I've only kept the right side of the bar with the name of the session and CUP and that's all I need, but the background line goes through anyway. Is there any way to get rid of it or make it fully transparent? 
Thanks

**Comment by 89iuv** [comment]
Yes. Take a look over here: https://github.com/catppuccin/tmux?tab=readme-ov-file#override-the-default-status-background-color

Override the default status background color

```sh
set -g @catppuccin_status_background "theme"
This will overwrite the status bar background:
```

"theme" will use the color from the selected theme
"default" will make the status bar transparent
use hex color codes for other colors
Note: you need to restart tmux for this to take effect:

```
tmux kill-server & tmux
```sh

Please let me know if this works for you.

**Comment by shalawfatah** [comment]
Thanks @89iuv that works perfectly with "default"
