### ISSUE TITLE
Feature request: Window connect seperator 

### ISSUE THREAD

**Issue by ian-vu** [catppuccin/tmux#177]
Hey 👋👋, I am looking for the ability to connect the window separators similar to how the current status separators work. I am not sure if it is currently supported.

Currently there is support for the option `catppuccin_status_connect_separator "yes"` which allows for no gaps between the modules.  I am looking for the same effect but for the windows.

Hopefully my screenshot better expresses what I am looking for. 

![CleanShot 2024-03-29 at 20 22 56@2x](https://github.com/catppuccin/tmux/assets/42108124/a2a714b1-3f87-4005-aa4c-680af45c4ca0)

**Comment by MykhailoSukhostavets** [comment]
Just created PR, for now problem that I see is with most right separator. To fix this dracula tmux uses fixed icon that renders before all windows. 
In this example from dracula icon shows current session (on screenshot only one window, can be confusing)
<img width="1466" alt="image" src="https://github.com/catppuccin/tmux/assets/28440361/a14025ab-2e6b-4125-a447-2446dca2e1ac">

If we are interested in the same logic, I can create try to implement it

**Comment by ian-vu** [comment]
That looks awesome @MykhailoSukhostavets thanks for your work! 🙏 Perfectly what I was trying to express

**Comment by kjnsn** [comment]
This is supported by the tmux option `window-status-separator`. Closing
