### ISSUE TITLE
Issue with @catppuccin_pane_{left,right}_separator background

### ISSUE THREAD

**Issue by onaforeignshore** [catppuccin/tmux#180]
I have set the following:

```
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_pane_border_status "top"
set -g @catppuccin_pane_left_separator ""
set -g @catppuccin_pane_right_separator ""
set -g @catppuccin_pane_middle_separator " █"
set -g @catppuccin_pane_number_position "right"
set -g @catppuccin_pane_default_fill "number"
set -g @catppuccin_pane_border_style "fg=#24273a"
set -g @catppuccin_pane_active_border_style "fg=#24273a"
```

Looking closely at the picture, you can see a background behind the separator where there should be none.

<img width="1148" alt="Screenshot 2024-03-31 at 18 20 03" src="https://github.com/catppuccin/tmux/assets/704406/fd4ac2c5-f64a-4df9-b3d5-5b3e879cb590">

**Comment by guedesfelipe** [comment]
@onaforeignshore I made a fork and create a tag that works for me...

Install:
`set -g @plugin 'guedesfelipe/catppuccin_tmux#1.0.0'`

Tag 1.0.0 rollback to commit [e80cb735bbcd264ff971fdf7e58b219b60286c81](https://github.com/catppuccin/tmux/commit/e80cb735bbcd264ff971fdf7e58b219b60286c81)

@vdbe @89iuv Maybe we need to use tags at each changes to not break our envs xD

**Comment by vn7n24fzkq** [comment]
@guedesfelipe This works for me. Thanks!
before:
<img width="1503" alt="image" src="https://github.com/catppuccin/tmux/assets/20241522/799e1318-2917-43fd-8d09-68c5a20cbae1">
after:
<img width="1503" alt="image" src="https://github.com/catppuccin/tmux/assets/20241522/f0eb6aee-70b5-4e6f-bf55-91587a65e856">

**Comment by davidfmatheson** [comment]
I flipped to your fork, and then back to
```
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
```

and it went from odd background colors back to normal (sorry, neglected to take a screenshot). Thanks for the help!

**Comment by vdbe** [comment]
@vn7n24fzkq If you make an issue with your config I can try to find the problem.
From you screenshots it seems like config 3 with a custom background color and top status bar which works fine.

![image](https://github.com/catppuccin/tmux/assets/44153531/59d066ed-546c-42bc-a710-06d23785e83f)
