### ISSUE TITLE
can't activate catppucin/tmux

### ISSUE THREAD

**Issue by Trid-collab** [catppuccin/tmux#181]
I am trying to install catppucin/tmux wihout any success. 
 I have installed tmux on my macbook using brew install. 
Then I have set my tmux config folder on ~/.config/tmux
The plugins folder is in ~/.config/tmux/plugins with my tmux.conf residing in ~/.config/tmux/

However when I try to install catppucin/tmux in my tmux.conf - nothing seems to happen and whenI relod tmux config I get the following error and can't install the catppucin plugin 
`~/.config/tmux/plugins/tpm/tpm' returned 127`

However I try to install someother color scheme like Darcula it seems to work under above mentioned setup

Need help to correct this issue and install catppucin/tpm

**Comment by Trid-collab** [comment]
Problem solved

**Comment by CristianArean** [comment]
How you solved it?

**Comment by vdbe** [comment]
@CristianArean see https://github.com/catppuccin/tmux/discussions/285
