### ISSUE TITLE
Battery Charging icon display incorrect

### ISSUE THREAD

**Issue by Zoket** [catppuccin/tmux#188]
I installed catppuccin theme in tmux and installed tmux-battery,but battery icon seems display incorrect when in charging。
![image](https://github.com/catppuccin/tmux/assets/28720943/d0d4af56-b743-4526-aa4f-246bd55f85e8)
Here is `.tmux.conf` about catppuccin:
```
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour 'frappe' # or latte, macchiato, mocha

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "application session battery"

set -g @plugin 'tmux-plugins/tmux-battery'
```
nerd-font is `font-meslo-lg-nerd-font` installed by brew.
I have no idea which icon i'm missing.

**Comment by vdbe** [comment]
Does that change fix the problem?

**Comment by Zoket** [comment]
> Does that change fix the problem?这样改能解决问题吗？

Yes,this change overwrite default icon with nerd-font like this:
![image](https://github.com/catppuccin/tmux/assets/28720943/2d1c5e7d-d3a9-4f0a-be8e-b825944bff21)
