### ISSUE TITLE
Tmux status bar is not the same as on the screenshots

### ISSUE THREAD

**Issue by okgolove** [catppuccin/tmux#19]
I've tried alacritty and wezterm, tmux status bar is not transparent in both terminals. I use MacOS. Is it expected behaviour?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/36846182/197476470-458e1083-870d-455e-970f-0a20f34672a6.png">

**Comment by Je12emy** [comment]
Looks like you need a patched font, check: https://www.nerdfonts.com/

**Comment by okgolove** [comment]
Switched to one of the nerd fonts, it's still is not transparent 

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/36846182/198973152-467dbdce-5681-4243-8c7f-2fb92e806a9e.png">

**Comment by okgolove** [comment]
@rogeruiz hm, may be this is a bug of my vision :D
Anyway, thank everyone for help, at least I fixed fonts.

**Comment by Je12emy** [comment]
@okgolove Here's a screenshot of TMUX in my terminal, you may need to tweak your config.

![image](https://user-images.githubusercontent.com/34408108/212498533-142c6b97-a6bd-4f9e-8426-f162dee23ff0.png)

Here's my tmux config for reference: https://github.com/Je12emy/dotfiles/tree/main/config/tmux
