### ISSUE TITLE
Catppuccin TMUX Status Bar Position

### ISSUE THREAD

**Issue by hutgrabber** [catppuccin/tmux#190]
How can I move the status bar to the top? The Dracula theme allows you to do this via the following command:

`set -g @dracula-fixed-location "top"`

How can I do the same thing in Catppuccin TMUX?

**Comment by mklbravo** [comment]
I don't know what the Dracula theme option does or if there is any Catppuccin custom option for that, but in order to place the status bar on top I use the following tmux option:

`set -g status-position top` 

I hope this will be helpful.
