### ISSUE TITLE
Feature request: Add empty line below status bar

### ISSUE THREAD

**Issue by halexandru11** [catppuccin/tmux#192]
Hi,

I was wondering if it is possible to add support for a empty line bellow the status bar.

* **This is how it looks right now**
![Screenshot from 2024-04-17 14-10-20](https://github.com/catppuccin/tmux/assets/77728536/f114624e-4e2d-4352-82f8-66a5c40b964a)

* **This is how i would like it to look**
![Screenshot from 2024-04-17 14-12-41](https://github.com/catppuccin/tmux/assets/77728536/b0c6cae3-00d3-4f6e-9f89-c0ae2fddd979)

I tried to use this from [Stack Exchange - tmux-status-line-with-blank-line-on-top](https://unix.stackexchange.com/a/680462), but it doesn't work. Every time i reload the tmux configuration, the status bar has 2 lines for half a second and then it gets reset to 1 line.

```tmux
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[1]' ''
set -g status 2
```

If I remove ```set -g @plugin 'catppuccin/tmux'``` from my configuration, the status bar will have 2 lines, but i lose this awesome theme.

**Comment by vdbe** [comment]
Are those lines at the very end of your tmux.conf (behind all the tpm lines)?

The stackoverflow post links a github issue maybe try the last suggested solution from that.

**Comment by halexandru11** [comment]
I put those line after ```run '~/.tmux/plugins/tpm/tpm'``` and now it works perfectly.

Thank you very much @vdbe. I would of never thought to put them at the very end.

**Comment by ramedhis** [comment]
You don't really need this line:
```.tmux
set -Fg 'status-format[1]' '#{status-format[0]}'
```

Using these lines alone should work just fine:
```.tmux
set -g status 2
set -g status-format[1] ''
```
---
Out of curiosity, what color scheme are you using there, by the way (assuming you're using p10k)?

**Comment by halexandru11** [comment]
Thanks for the alternative solution @ramedhis.

I tweaked the p10k color scheme to my liking. You can find it on my [dotfiles](https://github.com/halexandru11/.dotfiles/blob/main/.config/zsh/.p10k.zsh) repo.
