### ISSUE TITLE
Gitmux module not working

### ISSUE THREAD

**Issue by pbakiewicz** [catppuccin/tmux#211]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Gitmux module doesn't show anything in cappuccin. It definitely works when I  run `gitmux` in shell but it shows nothing when I add it as catpuccin status modules right.

### Paste your configuration.

unbind C-b
set-option -g prefix C-a
set -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_status_modules_right "session gitmux application"

run '~/.tmux/plugins/tpm/tpm'

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
![image](https://github.com/catppuccin/tmux/assets/44153531/0c965f55-da8b-47e6-9d53-87d94a9db700)

Seems to work fine, used your exact config and also tmux 3.4.

Is your pane in a git repo if not you will see this:
![image](https://github.com/catppuccin/tmux/assets/44153531/82b32e9a-9e0e-4262-825a-aff565d637cc)

Can you provide the output of `tmux show-options -g status-right`?

**Comment by pbakiewicz** [comment]
Sure, this is the output:
```
status-right "#status-right "#[fg=#{?client_prefix,#f38ba8,#a6e3a1},bg=#1e1e2e,nobold,nounderscore,noitalics]█#[fg=#1e1e2e,bg=#{?client_prefix,#f38ba8,#a6e3a1},nobold,nounderscore,noitalics] #[fg=#cdd6f4,bg=#313244] #S#[fg=#313244,bg=#313244,nobold,nounderscore,noitalics]█#[fg=#f5c2e7,bg=#313244,nobold,nounderscore,noitalics]█#[fg=#1e1e2e,bg=#f5c2e7,nobold,nounderscore,noitalics] #[fg=#cdd6f4,bg=#313244] #W#[fg=#313244,bg=#313244,nobold,nounderscore,noitalics]█"
```

In the meantime if some had similiar problem I changed module I didn't use (host in my example) into gitmux, which works fine:

```
set -g @catppuccin_host_text "#(gitmux -cfg $HOME/.gitmux.conf \"#{pane_current_path}\")"
set -g @catppuccin_host_icon ""
```

**Comment by vdbe** [comment]
There is no gitmux in you status-right output.

this is my output:
```
status-right "#[fg=#{?client_prefix,#f38ba8,#a6e3a1},bg=default,nobold,nounderscore,noitalics]#[fg=#1e1e2e,bg=#{?client_prefix,#f38ba8,#a6e3a1},nobold,nounderscore,noitalics] #[fg=#cdd6f4,bg=#313244] #S#[fg=#313244,bg=#313244,nobold,nounderscore,noitalics]█#[fg=#a6e3a1,bg=#313244,nobold,nounderscore,noitalics]#[fg=#1e1e2e,bg=#a6e3a1,nobold,nounderscore,noitalics]󰊢 #[fg=#cdd6f4,bg=#313244] #(gitmux \"#{pane_current_path}\")#[fg=#313244,bg=#313244,nobold,nounderscore,noitalics]█#[fg=#f5c2e7,bg=#313244,nobold,nounderscore,noitalics]#[fg=#1e1e2e,bg=#f5c2e7,nobold,nounderscore,noitalics] #[fg=#cdd6f4,bg=#313244] #W#[fg=#313244,bg=#313244,nobold,nounderscore,noitalics]█"
```
notice the:
`... #[fg=#1e1e2e,bg=#a6e3a1,nobold,nounderscore,noitalics]󰊢 #[fg=#cdd6f4,bg=#313244] #(gitmux \"#{pane_current_path}\") ...`

are you sure you included it?

as for the fix the modules uses the same https://github.com/catppuccin/tmux/blob/c0564122384d85403f5064038282b87a325c1a5e/status/gitmux.sh#L9

except the `-cfg $HOME/.gitmux.conf ` part does gitmux work for you withouth that part?

**Comment by phortheman** [comment]
I was having a similar issue with gitmux but the solution was to update catppuccin/tmux. If you are using TPM do <prefix>-U to update all your plugins. The gitmux module is newish (#191) and you probably didn't update catppuccin/tmux which is why editing the host module worked for you!

**Comment by vdbe** [comment]
Trying to load a missing module should print an error. Made an issue for it.
