### ISSUE TITLE
Latest changes break plugin

### ISSUE THREAD

**Issue by srogozhin** [catppuccin/tmux#213]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

When I updated to the latest version (as of 9 hours ago reading this), 4a561f9f0841b782ac58cda26fef6d3ddbd5b6d2,  Catppuccin no longer loads. When I source the config, i get `~/.local/state/tmux/plugins/tpm/tpm' returned 1`.

In my plugins folder, i switched to commit, 2292669be300155652e6f8ef6d0312eb100c34d4 (before the color interpolation changes), and it started working normally.

For now, I have a workaround by keeping on commit, 2292669be300155652e6f8ef6d0312eb100c34d4, so no rush and thank you for all of your hard work 💪 .

> 

### Paste your configuration.

```
set-option -sa terminal-overrides ",xterm*:Tc"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# -n is short for the root table (no-prefix)
bind -n M-H previous-window
bind -n M-L next-window

# vi mode bindings
# -T <key-bind-table> <key> send-keys -X <action>
bind-key -T copy-mode-vi y send-keys -X copy-selection \; send-keys -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind is an alias of bind-key
bind -T copy-mode-vi W send-keys -X next-word \; send-keys -X begin-selection \; send-keys -X previous-word
#
#
# # opens splits with same directory as window
bind '"' split-window -c '#{pane_current_path}'
# bind-key by itself is the same as bind-key -T prefix
bind % split-window -h -c '#{pane_current_path}'
#
# # set global on all sessions
set -g mouse on
# # set global on all windows in session
setw -g mode-keys vi

set -g status-position top

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/state/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
run '~/.local/state/tmux/plugins/tpm/tpm'
```

### Attach screenshots.

Before latest update (2292669be300155652e6f8ef6d0312eb100c34d4)
<img width="1651" alt="working" src="https://github.com/catppuccin/tmux/assets/102387839/6cfc60a3-025d-45f5-a76d-29a4923bce21">

After latest update (4a561f9f0841b782ac58cda26fef6d3ddbd5b6d2)
<img width="1648" alt="not working" src="https://github.com/catppuccin/tmux/assets/102387839/fc7ffb05-0333-4781-af35-a35256714a15">

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
Are you an macos?

**Comment by vdbe** [comment]
Can you test if #214 fixed (already in main)

**Comment by vdbe** [comment]
Can anyone on macos confirm that the fix worked?

**Comment by thehatchcloud** [comment]
I just tried loading from your fork @vdbe, and it loaded successfully.

**Comment by vdbe** [comment]
Sorry meant this repository, but the fix made it already in the main of my fork so no worries.

@thehatchcloud Thank you very much

Going to leave this open for a few more days just to be safe.

**Comment by thehatchcloud** [comment]
Sure thing. I can try from here too. How do you install a plugin from a different commit or branch? I don't know the syntax to do that.

**Comment by vdbe** [comment]
`set -g @plugin 'catppuccin/tmux'`
The fix already made it to the main branch of the plugin. (You also already tested it by using my fork)

**Comment by vdbe** [comment]
It's installing the plugin named tmux. See #129

**Comment by thehatchcloud** [comment]
Thank you for the clarification. Now that I understand the naming context, I figured out what was going on.

The ~/.tmux/plugins/tmux folder was there but was empty. Because I didn't realize that was catppuccin, I never touched it. Once I read #129, I deleted the folder and re-ran updates, and everything started working as expected.

Thanks again for the help! 🥇
