### ISSUE TITLE
Bell status icon does not display properly

### ISSUE THREAD

**Issue by uraza** [catppuccin/tmux#217]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Hello.

To monitor the execution of some commands of interest, I ring the bell when they complete and display the corresponding bell icon in the tmux status bar.

When the window that triggers the bell is not the previous window, the bell status icon does not display properly, it is like it has been cropped on the right side.

Basic configuration and screenshots below.

Thanks for your inputs!

### Paste your configuration.

```
set -g default-terminal "screen-256color"
set -sg terminal-overrides ",*:RGB"

set-window-option -g window-status-bell-style none
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "catppuccin/tmux"

run "~/.config/tmux/plugins/tpm/tpm"
```

### Attach screenshots.

Let's say that thare are 3 windows open, numbered 0, 1 and 2.

- When the window that rings the bell is the previous one, it displays correctly:

Run "sleep 5s && echo -e '\a'" in window 0 then move to window 1.

![image](https://github.com/catppuccin/tmux/assets/3456223/04d51491-1ee2-422f-aa91-c2c829afe9ee)

- When the window that rings the bell is not the previous one, it does not display correctly:

Run "sleep 5s && echo -e '\a'" in window 0 then move to window 1 then move to window 2.

![image](https://github.com/catppuccin/tmux/assets/3456223/4c66e63a-1365-48d9-b3b1-cb86ddbe35d7)

### What tmux version are you seeing the issue on?

tmux 3.3a

**Comment by vdbe** [comment]
This is a font problem.
Some solution's:
- Change font
- Add a space being the icon `set -g @catppuccin_icon_window_bell "󰂞 "`

**Comment by uraza** [comment]
Adding an extra space is working great! 

I did not even try because I thought it was the default based on https://github.com/catppuccin/tmux?tab=readme-ov-file#override-windows-status-icons 😅

Thanks a lot @vdbe !

**Comment by vdbe** [comment]
Yea should update the examples to reflect the default some do others do not or at least specify the default.
