### ISSUE TITLE
better color for load module

### ISSUE THREAD

**Issue by Thomas-Philippot** [catppuccin/tmux#218]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

Load module display load info in green color.

Color seems to be loaded for all the modules the same way.

`local show_right_separator="#[fg=$color,bg=default,nobold,nounderscore,noitalics]$status_right_separator"`

I don't know where to change this green color, but I thought it will be great to have the default "white" color.

![Capture d’écran du 2024-05-17 11-33-10](https://github.com/catppuccin/tmux/assets/36050256/8aaf8bdf-4d9e-448e-bec6-907b4dcc7647)

**Comment by vdbe** [comment]
The color for the load module is set by tmux-loadavg (https://github.com/jamesoff/tmux-loadavg/blob/master/scripts/display_load.sh) don't know how to override this.

For most other modules the fg can be set using `set -g @catppuccin_[module_name]_text/icon "#[fg=<hex/#{thm_<color>}>]<original text/icon>"`
