### ISSUE TITLE
Status bar background being automatically grayscaled

### ISSUE THREAD

**Issue by sklbz** [catppuccin/tmux#221]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I've tried a lot of  value for the `status_background` but it is always pure gray. How can i get it transparent or the same color as my background ?

### Paste your configuration.

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g @catppuccin_status_background "default" 
set -g @catppuccin_flavor "mocha"

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_fill "icon"

run -b '~/.tmux/plugins/tpm/tpm'

### Attach screenshots.

![Capture d’écran (1)](https://github.com/catppuccin/tmux/assets/122096315/c5a9cd34-afcc-42cb-aeec-a66fd54e4290)

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
What terminal are you using and does the terminal have transparency?
![image](https://github.com/catppuccin/tmux/assets/44153531/6b8272f7-1672-4f7e-adf3-47deeedba353)
Your config in alacritty with opacity?

**Comment by sklbz** [comment]
I was using the windows terminal preview (I'm on WSL) with the default config.

Strangely this problem went away with the nightly build of the terminal.
