### ISSUE TITLE
Rename window still doesn't work

### ISSUE THREAD

**Issue by kareulo-DEVGO-Studio** [catppuccin/tmux#227]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Renaming a window does not reflect on the bar.

### Paste your configuration.

```
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set-option -g renumber-windows on

set -ga terminal-overrides ",xterm-256color*:Tc"

set -g pane-border-style bold

set -g status-position top

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @plugin "catppuccin/tmux"
set -g @plugin "tmux-plugins/tmux-battery"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tpm"

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "user host battery date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%A, %Y-%m-%d"

run '~/.tmux/plugins/tpm/tpm'
```

### Attach screenshots.

https://github.com/catppuccin/tmux/assets/166430582/a490e822-3c9f-41a4-b416-d7a6e504ad10

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
```tmux
# Window
set -g @catppuccin_window_current_text "#{window_name}"
set -g @catppuccin_window_default_text "#{window_name}"
``` Add these lines to your config

**Comment by kareulo-DEVGO-Studio** [comment]
> ```shell
> # Window
> set -g @catppuccin_window_current_text "#{window_name}"
> set -g @catppuccin_window_default_text "#{window_name}"
> ```
> 
> Add these lines to your config

Damn, that was fast! Thank you!

**Comment by hello-smile6** [comment]
> ```shell
> # Window
> set -g @catppuccin_window_current_text "#{window_name}"
> set -g @catppuccin_window_default_text "#{window_name}"
> ```
> 
> Add these lines to your config

That only works for the active window, not inactive windows.

**Comment by audience6killer** [comment]
> ```shell
> # Window
> set -g @catppuccin_window_current_text "#{window_name}"
> set -g @catppuccin_window_default_text "#{window_name}"
> ```
> 
> Add these lines to your config

Is there a way to do it also for inactive windows?

**Comment by kjnsn** [comment]
```
set -g @catppuccin_window_current_text "#{window_name}"
set -g @catppuccin_window_text "#{window_name}"
```

**Comment by BernatRubio** [comment]
> I added the two lines above and my window name is not changing. I should note the window name displayed is actually the static hostname given from the hostnamectl command. When I try to change it, it displays the original name of "bash" and then allows me to enter the new name but it does not persist to the actual window name which remains the hostnamectl (static hostname).
> 
> Here is my configuration: $ cat /home/neo/.config/tmux/tmux.conf
> 
> # tmux configuration file
> # try to set 24 bit color providing the terminal supports it
> set-option -sa terminal-overrides ",xterm*:Tc" set -g mouse on
> 
> # start windows and panes from 1 not 0
> set -g base-index 1 set -g pane-base-index 1 set-window-option -g pane-base-index 1 set-option -g renumber-windows on
> 
> set -g [@plugin](https://github.com/plugin) 'tmux-plugins/tpm' set -g [@plugin](https://github.com/plugin) 'tmux-plugins/tmux-sensible' set -g [@plugin](https://github.com/plugin) 'catppuccin/tmux'
> 
> # change default prefix key
> unbind C-b set -g prefix C-t bind C-t send prefix
> 
> run '~/.tmux/plugins/tpm/tpm'
> 
> # window name was not changing, the fix is given below
> # [#227](https://github.com/catppuccin/tmux/issues/227)
> # Window
> set -g @catppuccin_window_current_text "#{window_name}" set -g @catppuccin_window_text "#{window_name}"
> 
> Please kindly let me know. Thanks.

I encountered the same issue where I was unable to rename tmux windows, and the default window name was initially set to the hostname. I found a workaround that resolved this for me.

The solution was adapted from [this comment](https://github.com/catppuccin/tmux/discussions/317#discussioncomment-11064512), and here’s my working .tmux.conf:
```
set-option -g status-position top
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g status-style bg=default

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{default},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{default},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{default}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{default},bold"
set -gF window-status-separator "#[bg=#{default},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"
```
I hope this helps!

**Comment by qs-lzh** [comment]
> > 我添加了上面两行代码，但我的窗口名称没有改变。需要注意的是，显示的窗口名称实际上是 hostnamectl 命令提供的静态主机名。当我尝试更改它时，它会显示原始名称“bash”，然后允许我输入新名称，但不会保留实际的窗口名称，而是保留 hostnamectl（静态主机名）。
> > 这是我的配置：$ cat /home/neo/.config/tmux/tmux.conf
> > # tmux 配置文件
> > # 如果终端支持，请尝试设置 24 位颜色
> > 设置选项 -sa 终端覆盖“，xterm*:Tc”设置 -g 鼠标开启
> > # 从 1 而不是 0 开始窗口和窗格
> > 设置 -g 基索引 1 设置 -g 窗格基索引 1 设置窗口选项 -g 窗格基索引 1 设置选项 -g 重新编号窗口
> > 设置 -g [@plugin](https://github.com/plugin) 'tmux-plugins/tpm' 设置 -g [@plugin](https://github.com/plugin) 'tmux-plugins/tmux-sensible' 设置 -g [@plugin](https://github.com/plugin) 'catppuccin/tmux'
> > # 更改默认前缀键
> > 解除绑定 Cb 设置 -g 前缀 Ct 绑定 Ct 发送前缀
> > 运行'~/.tmux/plugins/tpm/tpm'
> > # 窗口名称没有改变，修复方法如下
> > # [#227](https://github.com/catppuccin/tmux/issues/227)
> > # 窗户
> > 设置 -g @catppuccin_window_current_text“#{window_name}” 设置 -g @catppuccin_window_text“#{window_name}”
> > 请告知我。谢谢。
> 
> 我建议在像这样之前添加一个空格`#{`：
> 
> 设置 -g @catppuccin_window_current_text " #{window_name}" 设置 -g @catppuccin_window_text " #{window_name}"
> 
> 效果很好，谢谢！

That WORKS for me , Thanks!
