### ISSUE TITLE
status bar looking weird with misaligned items 

### ISSUE THREAD

**Issue by CoreiaTENEBROSO** [catppuccin/tmux#228]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I've tried everything from tweaking configurations in Konsole to changing the font, font size and nothing seems to fix it

### Paste your configuration.

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory host date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm/tpm'

### Attach screenshots.

![image](https://github.com/catppuccin/tmux/assets/98190040/20e2891d-0e41-40da-8992-0fee5c68aa6f)

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
That is an issue with the combination of your font, font-size and maybe zoom

**Comment by CoreiaTENEBROSO** [comment]
any font u can recommend me then?

**Comment by vdbe** [comment]
I use Alacritty 'CommitMono Nerd Font Mono' Size 10

**Comment by CoreiaTENEBROSO** [comment]
yep, switching to alacritty fixed it, seems like it was an konsole issue

**Comment by CoreiaTENEBROSO** [comment]
btw, alacritty seems to be way faster than konsole

**Comment by CoreiaTENEBROSO** [comment]
Thanks for the help
