### ISSUE TITLE
Mosh vs SSH status bar rendering

### ISSUE THREAD

**Issue by Kristijan** [catppuccin/tmux#229]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I run tmux on a remote Linux host, and when using `mosh` to connect to the server, the rendering of the tmux status bar wraps.

<img width="1226" alt="image" src="https://github.com/catppuccin/tmux/assets/234730/7a52b703-870b-4778-a600-507844bec11f">

Connecting via `ssh`, it renders correctly.

<img width="1220" alt="image" src="https://github.com/catppuccin/tmux/assets/234730/c64173ea-30fd-458f-bc3b-d7ac52ffe11b">

I'd say it's more of a mosh problem than a configuration one, but raising the issue in case someone has come across this before and can provide any insights in using this theme along with mosh.

### Paste your configuration.

I've provided the catppuccin configuration section of my `.tmux.conf` file, but the entire contents can be provided if it's of benefit.

```
# catppuccin theme (https://github.com/catppuccin/tmux)
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
## window settings
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator "█ "
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_status_icon_enable "yes"
## pane settings
set -g @catppuccin_pane_active_border_style '#{?pane_in_mode,fg=#{thm_yellow},#{?synchronize-panes,fg=#{thm_red},fg=#{thm_blue}}}'
## status settings
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_modules_right "date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
## module settings
set -g @catppuccin_date_time_text "%d-%m-%Y %H:%M"
```

### What tmux version are you seeing the issue on?

tmux 3.3a

### Any additional comments?

I'm using the following terminal and font.

- Warp terminal (v0.2024.05.28.08.02.stable_00)
- MonaspiceAr Nerd Font Mono (font size: 13, line height 1.2)

I've tried iTerm2 and different fonts/line heights, but it hasn't made a difference to the status wrapping.

**Comment by vdbe** [comment]
It does not only wrap around see the 4, from what is that 4 even? The bar wouldn't even need to wrap without it (if you ignore that tmux with just shift status right 1 char to the left).

Possible (untested) clean solution experiment with some `set  -g default-terminal` and `set -ga terminal-overrides` combinations in your tmux config.

Hacks that might work (no idea don't use must/know how it works) adding a space at the end of the status bar maybe something like this (again untested):
`set -Fg 'status-format[0]' '#{status-format[0]}<add here padding>'`/`set -Fg 'status-format' '#{status-format}<add here padding>'` (syntax is from here https://unix.stackexchange.com/a/680462) might need to change the fg/bg styling so that mosh sees it as empty space with `#[fg=<some color/default?>,bg=<some color/default?>,nobold,nounderscore,noitalics]`.

There are many issues for tmux/other cli applications on mosh ask it there.

**Comment by Kristijan** [comment]
Thanks for getting back to me @vdbe. I'll close the issue, and continue to play around with my configuration to see if I can get something workable. Should I find something, I'll post back here for others that come on by.

**Comment by Nelyah** [comment]
@Kristijan Any chance you've been able to find a solution for this? :) I'm experiencing the exact same behaviour (also probably because of mosh issue)

**Comment by Kristijan** [comment]
> @Kristijan Any chance you've been able to find a solution for this? :) I'm experiencing the exact same behaviour (also probably because of mosh issue)

Unfortunately not. I didn't spend a heap of time tinkering trying to determine what was the cause. I'm still using the theme, just over SSH. I'd love to switch back to mosh though, so if you figure it out, do let me know.

**Comment by Nelyah** [comment]
Thanks for answering! Unfortunately I haven't been able to find the solution either for now. I also didn't have that much time to dive too deeply. 

I have a hunch it could be something to do with the `TERM` env variable, but I couldn't find something that worked. Maybe this has something to do with some nerdfonts not being supported by mosh?

**Comment by stmharry** [comment]
+1 for the issue. I notice that the tmux status line is smeared (mixed with the second last line), and particularly when inside neovim (inside tmux, via mosh session) the top line can sometimes be eaten by contents out of nowhere.

**Comment by kjnsn** [comment]
This is definitely not anything we have the ability to fix. Feel free to +1 https://github.com/mobile-shell/mosh/issues/1041
