### ISSUE TITLE
Issue with transparency when setting @catppuccin_status_background "default"

### ISSUE THREAD

**Issue by 64rl0** [catppuccin/tmux#242]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

change `module_builder.sh` line 10
`local show_text="#[fg=$thm_fg,bg=$thm_gray] $text"`
to 
`local show_text="#[fg=$thm_fg,bg=default] $text"`

this will allow to set the bg color of the space character between the icon and the text to the default bg color of the terminal

**Comment by vdbe** [comment]
It looks like that has no side effects. Can you add 2 screen shots and your config to see what it would change?

**Comment by 64rl0** [comment]
sure, here it is


<img width="1213" alt="2024-07-07_14-19-36" src="https://github.com/catppuccin/tmux/assets/17791726/e23cc399-bbf4-4a06-b52c-1788de135913">

**Comment by vdbe** [comment]
Feel free to open a PR.
