### ISSUE TITLE
Unknown command: local

### ISSUE THREAD

**Issue by Hidan0** [catppuccin/tmux#25]
Hey!
I used the maual installation and when opening tmux this il what I get: `/home/hidan0/.tmux.conf:25: unknown command: local`

**Comment by Hidan0** [comment]
I've found a work around by simply using `set-option -gq ` instead of `set` and ` set-window-option -gq ` instead of `setw`.
Ex:
`set status "on"` => `set-option -gq status "on"`
`setw clock-mode-colour "${thm_blue}"` => `set-window-option -gq clock-mode-colour "${thm_blue}"`

**Comment by ss77a** [comment]
cool thanks ill give that a try

**Comment by Hidan0** [comment]
I also removed the functions

**Comment by rogeruiz** [comment]
thanks for the update @Hidan0 and @ss77a I've merged in #22 since which is a major refactor of how things are done in the plugin.

**Could you let me know if a fresh install of the plugin still causes the problem?** 

Thanks!

**Comment by rogeruiz** [comment]
> I've found a work around by simply using `set-option -gq ` instead of `set` and `set-window-option -gq` instead of `setw`. Ex: `set status "on"` => `set-option -gq status "on"` `setw clock-mode-colour "${thm_blue}"` => `set-window-option -gq clock-mode-colour "${thm_blue}"`

this makes sense to me. I'm also curious what Shell you're using. The functions that you removed are wrappers around the Tmux commands you replaced them with. You may know this, but I figure I'd explain it for others you stumble across this Issue and the same bug you experienced.

**Comment by rogeruiz** [comment]
It's possible that you've also not run this using the Tmux Plugin Manager (TPM). That's the recommended way to install this plugin. We might be able to do more around supporting both ways. But it seems related to this solution in another project. https://github.com/wfxr/tmux-power/issues/1#issuecomment-652116634

**Comment by Hidan0** [comment]
> I'm also curious what Shell you're using.

I'm using zsh and I tried with bash too, but this should't be a problem given the initial declaration `#!/usr/bin/env bash`, or am I missing something?

**Comment by Hidan0** [comment]
> **Could you let me know if a fresh install of the plugin still causes the problem?**

A fresh install of #22 with TPM doesn't cause the issue

**Comment by ss77a** [comment]
Yes!! Oh yes indeed nice work. My terminal is kitty with ohmyzsh. I had named my folder incorrectly before.

**Comment by rogeruiz** [comment]
Closing this issue since it seems to be working now. I think if any of y'all want to add some documentation around troubleshooting we'd appreciate it. Eventually I may get around to doing it myself. Thanks!
