### ISSUE TITLE
Status panel background missing

### ISSUE THREAD

**Issue by awwsomepotato** [catppuccin/tmux#252]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Status panel module background missing when `@catppuccin_status_connect_separator` is disabled, when it's enabled the problem goes away. Is also present when using Config 3 from the README.

### Paste your configuration.

set -g @plugin "tmux-plugins/tmp"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"

# catppuccin
set -g @plugin "catppuccin/tmux"
set -g @catppuccin_flavour "macchiato"
set -g @catppuccin_status_background "default"

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_current_background "#{thm_gray}"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_directory_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "user host session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g status-position bottom

set -as terminal-features ",alacritty*:RGB"
set -g mouse on
set -g default-shell /bin/zsh

# start things at 1 not 0 (easier to reach)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# shift alt + l or h switch window
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run "~/.local/share/tmux/plugins/tpm/tpm"

### Attach screenshots.

![image](https://github.com/user-attachments/assets/57f2d1fa-08b8-4015-80ab-3266f42dbeb6)

### What tmux version are you seeing the issue on?

tmux 4.4

**Comment by vdbe** [comment]
For default config 3 is it without any additional settings?
If so I missed something in #250

**Comment by vdbe** [comment]
I see the issue accidentally moved the show_text in that pr. My apologies will fix it as soon as possible.
