### ISSUE TITLE
WSL tmux catppuccin not working after rechanging repo name via FORKing into my repo

### ISSUE THREAD

**Issue by mike-rambil** [catppuccin/tmux#261]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Due to the naming conflict, I tried to change the name from `tmux` to `tmux-catppuccin`, but still even after the plugin is downloaded with the `ctrl + B, I`, the plugin theme are not being used by tmux.

### Paste your configuration.

```
# run '~/.config/tmux/plugins/tmux-catppuccin/catppuccin.tmux'

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^B
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mike-rambil/tmux-catppuccin'
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M"

run '~/.config/tmux/plugins/tpm/tpm'

```

### Attach screenshots.

# Before `ctrl + B, I`
![image](https://github.com/user-attachments/assets/012acf1c-ee28-4848-af17-379c52f71973)

# When pressing the button, it refreshes
![image](https://github.com/user-attachments/assets/ec5445aa-2db8-4faa-85c1-0a8130cae7b7)

# Afterwards the packages are downloaded
![image](https://github.com/user-attachments/assets/ae14d08e-01cf-46de-bd34-b805b414700d)

### What tmux version are you seeing the issue on?

tmux 3.2a

### Any additional comments?

My version as listed above is tmux 3.2a. Don't know if this is a problem?

I have also commented out in the config, line 1 as I assume I don't have to source the file since it's automated by tpm? sourcing it here never helped either(I tried uncommenting it to see if that helps)

**Comment by vdbe** [comment]
`rm -rf ~/.tmux/plugins` and `rm -rf $XDG_CONFIG_HOME/tmux/plugins` like the response in the pinned comment suggested and try again.

Also there should be no conflict eith another plugin looking at the provided config.
