### ISSUE TITLE
`catppuccin_status_modules_left/right` empty space treated as a module

### ISSUE THREAD

**Issue by wojciech-kulik** [catppuccin/tmux#263]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

When I reload my config I get:
```
catppuccin warning: module  not found
catppuccin warning: module  not found
```

Everything seems to be working, but the error is annoying.

### Paste your configuration.

```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Settings
set -g status-position "top"

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_current_background "#363A4F"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,*,}"

set -g @catppuccin_status_modules_right " "
set -g @catppuccin_status_modules_left "session "
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator " | "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
```

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
Do you also get the warning when removing the trailing space from modules left and setting right yo `""`?

**Comment by wojciech-kulik** [comment]
You are right, it's caused by:
```
set -g @catppuccin_status_modules_right " "
set -g @catppuccin_status_modules_left "session "
```

I replaced it with:
```
set -g @catppuccin_status_modules_right ""
set -g @catppuccin_status_modules_left "session"
```

and warnings are gone, but now the default modules appear on the right side. How can I  remove them?

**Comment by vdbe** [comment]
> and warnings are gone, but now the default modules appear on the right side. How can I remove them?
 
Setting a ln option to `"null"` will clear/remove it without falling back to the default.
https://github.com/catppuccin/tmux?tab=readme-ov-file#removing-a-specific-module-option

**Comment by wojciech-kulik** [comment]
Works great now! Thank you 🍻 !

**Comment by vdbe** [comment]
Is still an error in the README, will fix later.
And need to check if a module is not just empty space before trying to load it.
