### ISSUE TITLE
How do I change the default fg white color on my status bar?

### ISSUE THREAD

**Issue by gordonn** [catppuccin/tmux#286]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

I cant seem to directly edit the themes file without causing a error and there are no configuration options that show how to do it.

**Comment by gordonn** [comment]
To add context I want it to change it to a gruvbox color

**Comment by vdbe** [comment]
Currently not possible without change the theme files

**Comment by gordonn** [comment]
> Currently not possible without change the theme files

Thanks for the confirmation, I will just create my own fork with custom themes then
