### ISSUE TITLE
Use status-fg

### ISSUE THREAD

**Issue by vdbe** [catppuccin/tmux#287]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

We currently set `status-bg` and use the `[bg=default]` but do not set `status-fg` which results in using `[fg=$thm_fg]`.

when using `[fg=default]` users would be able to change the default it's however not perfect since the `fg` color is often something other then `$thm_fg`.

**Comment by kjnsn** [comment]
The `status-{fg,bg}` options are marked for deprecation by tmux, will not do
