### ISSUE TITLE
catppuccin warning

### ISSUE THREAD

**Issue by srgsanky** [catppuccin/tmux#293]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I keep getting this warning even though I am not using `catppuccin_window_status_enable` or `catppuccin_window_status_icon_enable`.

```
catppuccin warning: "@catppuccin_window_status_enable" and "@catppuccin_window_status_icon_enable" has been replaced by
       "@catppuccin_window_status" with the options "no", "icon" and "text"
```

Can you help me avoid this warning?

### Paste your configuration.

Full configuration at https://github.com/srgsanky/tmux/blob/main/tmux.conf.

Here is the catppuccin specific ones

```sh
set -g @catppuccin_flavor 'mocha' # default is mocha
set -g @plugin 'catppuccin/tmux' # Theme

set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"

# every window
# See below for an explanation of the conditional
set -g @catppuccin_window_default_text "#{?#{==:#T,#{host}}, #W , #T: #W }"
set -g @catppuccin_window_default_fill "number"
# Got the dull color from https://www.color-hex.com/color-palette/80211
set -g @catppuccin_window_default_color "#c9e9e7"
set -g @catppuccin_window_default_background "black"

# only current window
set -g @catppuccin_window_current_text "#[fg=orange,bold,reverse]#{?#{==:#T,#{host}},     #W#F     ,     #T: #W#F     }"
set -g @catppuccin_window_current_fill "number" # number, all , none
```

### What tmux version are you seeing the issue on?

tmux next-3.5

**Comment by vdbe** [comment]
Check the migration guide issue

**Comment by vdbe** [comment]
My bad you are not using any of them will fix

**Comment by srgsanky** [comment]
Thanks!

For the time being, if I explicitly set the config I don't get the warning

```
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_status_icon "icon"
```

**Comment by vdbe** [comment]
Sorry for the trouble
