### ISSUE TITLE
status bar fonts

### ISSUE THREAD

**Issue by BrunDerSchwarzmagier** [catppuccin/tmux#3]
My status bar isn't displaying properly (I think it's supposed to be some sort of semicircle?). What are the required fonts?
![Jan21-140140](https://user-images.githubusercontent.com/94010360/150605953-6a84e38f-6d56-4b84-8da3-3118f2462394.png)
.

**Comment by jtr860830** [comment]
> My status bar isn't displaying properly (I think it's supposed to be some sort of semicircle?). What are the required fonts?
> 
> ![Jan21-140140](https://user-images.githubusercontent.com/94010360/150605953-6a84e38f-6d56-4b84-8da3-3118f2462394.png)
> 
> .

https://github.com/ryanoasis/nerd-fonts

**Comment by BrunDerSchwarzmagier** [comment]
That fixed it. Cheers!
