### ISSUE TITLE
cant rename windows

### ISSUE THREAD

**Issue by AlejandroSanchez90** [catppuccin/tmux#303]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

when i hit prefix + , to change window name, it wont work, it will stay with defaults name

### Paste your configuration.

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
unbind r
bind r source-file ~/.tmux.conf
set -g @plugin 'catppuccin/tmux#latest'
set -g @catppuccin_flavour 'mocha'

# rezise panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z #Maximize panes

# list of plugin manager 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
# Use vim mode in terminal (prefix + [)
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# Persistent
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by vdbe** [comment]
Have you tried what is suggested in #227
