### ISSUE TITLE
Character sequence input when starting tmux in VS Code terminal

### ISSUE THREAD

**Issue by glecetre** [catppuccin/tmux#323]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

When starting Tmux with the Frappé theme in a VS Code terminal, a character sequence is input in stdin (not sent)

### Paste your configuration.

```
set -g base-index 1
set -g mouse on
setw -g pane-base-index 1

set-option -g allow-rename off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'

run '~/.tmux/plugins/tpm/tpm'
```

### Attach screenshots.

![image](https://github.com/user-attachments/assets/c23c85b5-266d-41af-afef-49b36793f8c2)
The tilde and purple diamond are part of my prompt, the rest appears when starting tmux.

### What tmux version are you seeing the issue on?

tmux 3.4

### Any additional comments?

Also tested with the Frappé theme, same result.

**Comment by kjnsn** [comment]
Can you comment out `run '~/.tmux/plugins/tpm/tpm'` and try again? Would like to confirm if this is an issue with tmux or this plugin

**Comment by glecetre** [comment]
I did and the issue persists

**Comment by kjnsn** [comment]
> I did and the issue persists.
> 
> I guess it could also be an issue with VS Code's terminal because it doesn't happen in iTerm2, but I don't know how to check that.

The vs code terminal is quite poor at advanced terminal features, and running tmux inside of it is probably not going to work well. 

Closing as this is not related to catppuccin at all
