### ISSUE TITLE
kube status is not load on init

### ISSUE THREAD

**Issue by davidshen84** [catppuccin/tmux#332]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

On entering tmux with kube status module, kube context is not show until force refresh tmux.conf file.

### Paste your configuration.

```sh
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"

set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'

# set -g @plugin 'jonmosco/kube-tmux'
# set -g status-right "#(/bin/bash $HOME/.config/tmux/plugins/kube-tmux/kube.tmux 250 red cyan)"

# theme config
set -g @plugin 'catppuccin/tmux#latest'
set -g @catppuccin_flavor 'frappe' # latte,frappe, macchiato or mocha
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application date_time kube"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
set -g @catppuccin_window_default_text "#{window_name}"
# set -g @catppuccin_status_modules_left "directory"

# set prefix
unbind C-b
unbind C-t
set -g prefix C-t
bind C-t send-prefix

# enable mouse
set -g mouse on

# split pane
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

### What tmux version are you seeing the issue on?

3.4-1ubuntu0.1

### Any additional comments?

If I load the kube module from https://github.com/jonmosco/kube-tmux directly without catppuccin, the kube context is show on tmux load.

After entering tmux and force reload the tmux.conf file. kube status is update after I issue kubectl command.

**Comment by kjnsn** [comment]
Hello! Could you try adding this after the run TPM line?

`set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_date_time}#{E:@catppuccin_status_kube}"`

**Comment by kjnsn** [comment]
> Only date and time are showing up. It is not after that I re-source tmux by `tmux source ~/.config/tmux/tmux.conf` That everything shows up correctly

I'm not surprised, TPM can be quite fiddly. I'd recommend manually `source`-ing the catppuccin plugin instead so the options are present in the running tmux server before the status line formats are expanded. If that doesn't work I'll look into it further :)
