### ISSUE TITLE
Battery status module not working

### ISSUE THREAD

**Issue by xronin01** [catppuccin/tmux#342]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Battery status module not working

### Paste your configuration.

```sh
### Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-features ",${TERM}:RGB"

### Mouse Support
set -g mouse on

### Status Bar Position
set -g status-position top

### Window Indexing
set -g base-index 1
set -g renumber-windows on

### Keymaps
unbind %
unbind '"'
bind v split-window -h
bind h split-window -v
bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Settings reloaded!"
# bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h' 'select-pane -L'
# bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j' 'select-pane -D'
# bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k' 'select-pane -U'
# bind-key -n C-l if -F "#{@pane-is-vim}" 'send-keys C-l' 'select-pane -R'
bind-key -n C-Left if -F "#{@pane-is-vim}" 'send-keys C-Left' 'select-pane -L'
bind-key -n C-Down if -F "#{@pane-is-vim}" 'send-keys C-Down' 'select-pane -D'
bind-key -n C-Up if -F "#{@pane-is-vim}" 'send-keys C-Up' 'select-pane -U'
bind-key -n C-Right if -F "#{@pane-is-vim}" 'send-keys C-Right' 'select-pane -R'
# bind-key -n M-h if -F "#{@pane-is-vim}" 'send-keys M-h' 'resize-pane -L 3'
# bind-key -n M-j if -F "#{@pane-is-vim}" 'send-keys M-j' 'resize-pane -D 3'
# bind-key -n M-k if -F "#{@pane-is-vim}" 'send-keys M-k' 'resize-pane -U 3'
# bind-key -n M-l if -F "#{@pane-is-vim}" 'send-keys M-l' 'resize-pane -R 3'
bind-key -n M-Left if -F "#{@pane-is-vim}" 'send-keys M-Left' 'resize-pane -L 3'
bind-key -n M-Down if -F "#{@pane-is-vim}" 'send-keys M-Down' 'resize-pane -D 3'
bind-key -n M-Up if -F "#{@pane-is-vim}" 'send-keys M-Up' 'resize-pane -U 3'
bind-key -n M-Right if -F "#{@pane-is-vim}" 'send-keys M-Right' 'resize-pane -R 3'
bind-key -n C-\\ if -F "#{@pane-is-vim}" 'send-keys C-\\\\' 'select-pane -l'
# bind-key -T copy-mode-vi 'C-h' select-pane -L
# bind-key -T copy-mode-vi 'C-j' select-pane -D
# bind-key -T copy-mode-vi 'C-k' select-pane -U
# bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-Left' select-pane -L
bind-key -T copy-mode-vi 'C-Down' select-pane -D
bind-key -T copy-mode-vi 'C-Up' select-pane -U
bind-key -T copy-mode-vi 'C-Right' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

### Sesh
bind-key "T" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

### Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux"
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"
set -g @plugin "Freed-Wu/tmux-battery#termux"
set -g @plugin "tmux-plugins/tmux-yank"

### Catppuccin Theme Configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "#11111b"
set -g @catppuccin_application_color "#11111b"
set -g @catppuccin_application_icon ""
set -g @catppuccin_date_time_text "%d-%m-%y %H:%M"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}#{E:@catppuccin_status_battery}#{E:@catppuccin_status_date_time}"

### TPM Installation
if "test ! -d $HOME/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm && $HOME/.config/tmux/plugins/tpm/bin/install_plugins'"

run "$HOME/.config/tmux/plugins/tpm/tpm"
```

### Attach screenshots.

![Screenshot_20241002-140326_Termux](https://github.com/user-attachments/assets/ecb7fa74-a49e-4a15-973a-f3ae8c637ec6)

### What tmux version are you seeing the issue on?

tmux 3.5

**Comment by kjnsn** [comment]
Does it work if you run run "~/.config/tmux/plugins/tpm/tpm" twice? You also need to set `status-right` and `status-left` _after_ TPM, or the user options that the plugin sets won't have been added yet.

The battery status works by looking for a string in the status line, and then replaces it in-place. If that string isn't set by the time you run the battery plugin, it won't work. Which is why you need to either run TPM twice, or run catppuccin, set the status, and _then_ load the battery module

**Comment by xronin01** [comment]
It didn't work

**Comment by xronin01** [comment]
![Screenshot_20241005-150654_Termux](https://github.com/user-attachments/assets/b66dad75-981b-42d7-b4a6-0b466ee3ea87)

**Comment by davidfmatheson** [comment]
I see the same behavior, complete with `#{battery_percentage}` in the status bar.

**Comment by kjnsn** [comment]
That makes sense, as you are only running tpm once. The status line is expanded by tmux, which will include the string the battery plugin is looking for. 

You need to expand it correctly and then load the battery plugin. Please see that plugins docs for more information. 

But this is working as intended from the perspective of this plugin

**Comment by davidfmatheson** [comment]
It appears that the battery plugin is loaded correctly, if I replace my status line config with

```
set -g status-right "#{E:@catppuccin_status_directory}#{E:@catppuccin_status_date_time}#{battery_percentage}"
```

I do get the right number (the faint `73%` on the end):

<img width="383" alt="image" src="https://github.com/user-attachments/assets/eb4461e4-10fa-4eea-9677-ce54ecbc87a8">

This is something that previously worked in 0.3.0. I will continue trying to suss it out, but it seems to be a problem [here](https://github.com/catppuccin/tmux/blob/main/status/battery.conf#L20) where you are setting it to the literal string `#{battery_percentage}`. Forgive my newness with tmux variables, but is that why you have `E:` before some vars, in the hopes that they are resolved and then resolved again?

**Comment by kjnsn** [comment]
Rhetorical question: how does the battery plugin add the percentage to the status line?

**Comment by kjnsn** [comment]
> I will continue trying to suss it out, but it seems to be a problem

This is working as per what the battery plugin expects. 

> where you are setting it to the literal string `#{battery_percentage}`. Forgive my newness with tmux variables, but is that why you have `E:` before some vars, in the hopes that they are resolved and then resolved again?

It's not hope. And the term is not "resolved", format strings are "expanded". There are unit tests, and I've carefully read the tmux man page. Like I said, you need to source catppuccin, set the status-right and left options, and _then_ load the battery plugin. It will not work any other way.

**Comment by davidfmatheson** [comment]
Great, so the crux of the solution is to make sure I'm using `set -gF` and not `set -g` when setting `status-right` and `status-left`, to ensure that the format string is expanded. That gives me back an actual percentage. Is it possible that you need `l:` by `battery_icon` as well, or perhaps I'm still doing something else wrong?

 
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/d3b16f42-9705-44fb-8c6d-9dace3f898b8">

**Comment by xronin01** [comment]
I got it to work, but the battery icon doesn't appear.
```sh
### Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-features ",${TERM}:RGB"

### Mouse Support
set -g mouse on

### Status Bar Position
set -g status-position top

### Window Indexing
set -g base-index 1
set -g renumber-windows on

### Keymaps
unbind %
unbind '"'
bind v split-window -h
bind h split-window -v
bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Settings reloaded!"
# bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h' 'select-pane -L'
# bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j' 'select-pane -D'
# bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k' 'select-pane -U'
# bind-key -n C-l if -F "#{@pane-is-vim}" 'send-keys C-l' 'select-pane -R'
bind-key -n C-Left if -F "#{@pane-is-vim}" 'send-keys C-Left' 'select-pane -L'
bind-key -n C-Down if -F "#{@pane-is-vim}" 'send-keys C-Down' 'select-pane -D'
bind-key -n C-Up if -F "#{@pane-is-vim}" 'send-keys C-Up' 'select-pane -U'
bind-key -n C-Right if -F "#{@pane-is-vim}" 'send-keys C-Right' 'select-pane -R'
# bind-key -n M-h if -F "#{@pane-is-vim}" 'send-keys M-h' 'resize-pane -L 3'
# bind-key -n M-j if -F "#{@pane-is-vim}" 'send-keys M-j' 'resize-pane -D 3'
# bind-key -n M-k if -F "#{@pane-is-vim}" 'send-keys M-k' 'resize-pane -U 3'
# bind-key -n M-l if -F "#{@pane-is-vim}" 'send-keys M-l' 'resize-pane -R 3'
bind-key -n M-Left if -F "#{@pane-is-vim}" 'send-keys M-Left' 'resize-pane -L 3'
bind-key -n M-Down if -F "#{@pane-is-vim}" 'send-keys M-Down' 'resize-pane -D 3'
bind-key -n M-Up if -F "#{@pane-is-vim}" 'send-keys M-Up' 'resize-pane -U 3'
bind-key -n M-Right if -F "#{@pane-is-vim}" 'send-keys M-Right' 'resize-pane -R 3'
bind-key -n C-\\ if -F "#{@pane-is-vim}" 'send-keys C-\\\\' 'select-pane -l'
# bind-key -T copy-mode-vi 'C-h' select-pane -L
# bind-key -T copy-mode-vi 'C-j' select-pane -D
# bind-key -T copy-mode-vi 'C-k' select-pane -U
# bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-Left' select-pane -L
bind-key -T copy-mode-vi 'C-Down' select-pane -D
bind-key -T copy-mode-vi 'C-Up' select-pane -U
bind-key -T copy-mode-vi 'C-Right' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

### Sesh
bind-key "T" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

### Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux"
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"
set -g @plugin "Freed-Wu/tmux-battery#termux"
set -g @plugin "tmux-plugins/tmux-yank"

### Catppuccin Theme Configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "#11111b"
set -g @catppuccin_application_color "#11111b"
set -g @catppuccin_application_icon ""
set -g @catppuccin_date_time_text "%d-%m-%y %H:%M"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

# Load catppuccin
run "$HOME/.config/tmux/plugins/tmux/catppuccin.tmux"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

### TPM Installation
if "test ! -d $HOME/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm && $HOME/.config/tmux/plugins/tpm/bin/install_plugins'"

run "$HOME/.config/tmux/plugins/tpm/tpm"
```

**Comment by xronin01** [comment]
> Great, so the crux of the solution is to make sure I'm using `set -gF` and not `set -g` when setting `status-right` and `status-left`, to ensure that the format string is expanded. That gives me back an actual percentage. Is it possible that you need `l:` by `battery_icon` as well, or perhaps I'm still doing something else wrong?
> <img alt="image" width="1088" src="https://private-user-images.githubusercontent.com/2395513/373921601-d3b16f42-9705-44fb-8c6d-9dace3f898b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTk0OTMsIm5iZiI6MTcyODMxOTE5MywicGF0aCI6Ii8yMzk1NTEzLzM3MzkyMTYwMS1kM2IxNmY0Mi05NzA1LTQ0ZmItOGM2ZC05ZGFjZTNmODk4YjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTYzOTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdjM2MwNWMzNzU1MmZjOGJjZGIzODhiZTA2YTIxYjE3ODk4YThmYzU3YmQwYzM1MjM1MTFiMzRjMTYwMDdkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FYARVHr0l4a58WT2ILQXCcGiOvYoRzuQjLrDK5AL6wQ">

![Screenshot_20241007-131906_Termux_1](https://github.com/user-attachments/assets/2fe043dc-89f4-4550-a31c-08e39cfe2184)

**Comment by davidfmatheson** [comment]
Yes, I was mistaken, `#{l:#{battery_icon}}` doesn't help. Not sure how to get it to appear. On your above configuration, @xronin01, does it work after a fresh install? If you run:

```
tmux kill-server
$HOME/.config/tmux/plugins/tpm/bin/clean_plugins`
tmux new-session -t test-session
```

Does it still work? Fair warning, `kill-server` will close all open tmux sessions.

**Comment by xronin01** [comment]
#{l:#{battery_icon}} works for me

**Comment by davidfmatheson** [comment]
> #{l:#{battery_icon}} works for me

You're right, I just tested it again from a fork I created. I created [a PR](https://github.com/catppuccin/tmux/pull/365) to fix it. To be clear, I'm just a user like you trying to figure out how to use this plugin since the post-0.3.0 rewrite.

Regarding the other question, does your setup still work after you kill all sessions and run clean_plugins?

**Comment by xronin01** [comment]
works 👍

**Comment by davidfmatheson** [comment]
Hmmm... how does it manage to do:

```
run "$HOME/.config/tmux/plugins/tmux/catppuccin.tmux"
```

if that file isn't there until you run tpm down on:

```
run "$HOME/.config/tmux/plugins/tpm/tpm"
```

That's the problem I'm having with my setup.

**Comment by kjnsn** [comment]
> Hmmm... how does it manage to do:
> 
> 
> 
> ```
> 
> run "$HOME/.config/tmux/plugins/tmux/catppuccin.tmux"
> 
> ```
> 
> 
> 
> if that file isn't there until you run tpm down on:
> 
> 
> 
> ```
> 
> run "$HOME/.config/tmux/plugins/tpm/tpm"
> 
> ```
> 
> 
> 
> That's the problem I'm having with my setup.

Running TPM doesn't install the plugins. Is the problem that you haven't installed the plugins you need?

**Comment by davidfmatheson** [comment]
Sorry, meant the line above:

```
if "test ! -d $HOME/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm && $HOME/.config/tmux/plugins/tpm/bin/install_plugins'"
```

If you start from a clean slate (i.e. after a `clean_plugins`), isn't that where the plugin files will actually be populated in `~/.config/tmux/plugins`? I'm in a pretty good state, though. Even loading from scratch, I just reload tmux config once and the battery icon and percentage show up. [This PR](https://github.com/catppuccin/tmux/pull/365) was needed to make the icon show up, though. I was following @xronin01's comment [here](https://github.com/catppuccin/tmux/issues/342#issuecomment-2397606155).
