### ISSUE TITLE
Basic window style spacing is off

### ISSUE THREAD

**Issue by gcapizzi** [catppuccin/tmux#348]
### Is there an existing issue outlining your problem?

- [x] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

The `basic` stile is missing some padding to the left of the window name. It should look like [this](https://github.com/catppuccin/tmux/blob/main/assets/window-basic.webp).

As a side note, in my opinion it should really look like [this](https://github.com/catppuccin/tmux/blob/main/assets/overview.png), without the big gap between windows, but that's a different issue.

### Paste your configuration.

```sh
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
```

### Attach screenshots.

![Image](https://github.com/user-attachments/assets/7ab01897-7b58-4748-aaa1-2f0948ebf1f6)

### What tmux version are you seeing the issue on?

tmux 3.5

**Comment by kjnsn** [comment]
If you don't set `@catppuccin_window_{default,current}_text`, how does it look?

**Comment by kjnsn** [comment]
You need to add a space before the `#W`

**Comment by kjnsn** [comment]
Also the spacing between windows is not controlled by this plugin, it is a tmux option `window-status-separator`. See https://man7.org/linux/man-pages/man1/tmux.1.html
