### ISSUE TITLE
Empty space under the status bar after maximizing the window

### ISSUE THREAD

**Issue by CWEzio** [catppuccin/tmux#349]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I find that after I maximize the window, there will be an empty space under the status bar.

If the window is not maximized, then, there will be no empty space under the status bar, as shown below:

![Screenshot from 2024-10-03 19-37-51](https://github.com/user-attachments/assets/df4eac40-22c6-48b5-9008-a4b623311147)

However, if I maximize the window, there will be an empty space below the status bar.
![Screenshot from 2024-10-03 19-38-55](https://github.com/user-attachments/assets/8b71aeab-474a-49ec-a5d6-140a9e23f0fd)

What I expect is that the status bar is on the bottom line and there is no empty space further below. 

### Paste your configuration.

```sh

# plugins
# options
set -g default-terminal "tmux-256color"
set -g mouse on
setw -g mode-keys vi
# The following options are from tmux-sensible
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0
# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5
# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs
# Focus events enabled for terminals that support them
set -g focus-events on


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'CWEzio/tmux-catppuccin'

# catppuccin
set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "yes"



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
# run '~/.config/tmux/plugins/tmux-catppuccin/catppuccin.tmux'
```

### What tmux version are you seeing the issue on?

tmux 3.4

### Any additional comments?
I am using a 16:10 screen.
Thank you!

**Comment by kjnsn** [comment]
Does this happen without catppuccin?

**Comment by kjnsn** [comment]
This is not related to catppuccin. Please see https://github.com/tmux/tmux/issues/3918
