### ISSUE TITLE
Rounded statusbar style not applied for selected window

### ISSUE THREAD

**Issue by paulwyszynski** [catppuccin/tmux#350]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

Hi!

Rouded window-status-style is not applied to current selected window. Is this expected behavior?

### Paste your configuration.

```
# Catppuccin theme config
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

```

### Attach screenshots.

![Screenshot 2024-10-03 at 3 48 25 PM](https://github.com/user-attachments/assets/9bf48e7e-7f32-4d3d-ae72-179f5c4aaf58)

### What tmux version are you seeing the issue on?

tmux 3.5

**Comment by kjnsn** [comment]
I'm unable to replicate this. Have you completely restarted the tmux server after changing your configuration?

**Comment by paulwyszynski** [comment]
@kjnsn I don't know what exacty the problem was, but after tweaking my config , killing tmux server and restarting, it started to work. I also deleted tmux plugin folder and fetched everything from scratch. And the theme styling was correct now.

Thanks!

In case anybody has the same issue, here's my current config which is partially built on another user:

```
# Catppuccin theme config
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
# Config from https://github.com/omerxx/dotfiles/blob/a2e5406eeb1e7854dc4b1149b618c01ed13a6c53/tmux/tmux.conf
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W "
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,() , }"
set -g @catppuccin_status_left_separator " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M"
# Top status bar config
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
```

Which basically looks like this:

![Screenshot 2024-10-04 at 11 20 22 AM](https://github.com/user-attachments/assets/68a2d5b1-d96c-4d74-bdff-5d8b236d866e)

**Comment by danimatuko** [comment]
I have the same issue [in my config](https://github.com/danimatuko/dotfiles/blob/main/tmux/tmux.confl)
Does this line should do the work?  `set -g @catppuccin_window_status_style "rounded"`
