### ISSUE TITLE
Custom module not longer works

### ISSUE THREAD

**Issue by rbhanot4739** [catppuccin/tmux#352]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I had a custom module to indicate pane synchronization, which no longer seems to work with the new version. The module shows up in the status bar, but its icon, colors, and text all seem to be messed up. Also when I sync panes the status color, text does not update.

The same code used to work with the previous version.

### Paste your configuration.

```
set -g @plugin 'catppuccin/tmux'
# add a custom to right status to indicate if panes are pane_synchronized
%hidden MODULE_NAME="pane_sync_status"


set -ogq "@catppuccin_${MODULE_NAME}_icon" "  "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "##{?pane_synchronized,#{E:@thm_red},#{E:@thm_green}}"
set -ogq "@catppuccin_${MODULE_NAME}_text" "#{?pane_synchronized,SYNC On,SYNC Off}"

source -F "/Users/rbhanot/.tmux/plugins/tmux/utils/status_module.conf"

set -g @catppuccin_flavor "macchiato"

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

set -g status-left "#{E:@catppuccin_status_session}"

set -g status-right "#{E:@catppuccin_status_directory}"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -g @catppuccin_date_time_text "%H:%M"
set -agF status-right "#{E:@catppuccin_status_pane_sync_status}"
```

### Attach screenshots.

![image](https://github.com/user-attachments/assets/42f41668-4e90-48f3-9abb-659f4b7e114a)

### What tmux version are you seeing the issue on?

3.4

**Comment by kjnsn** [comment]
Yes, a breaking change was introduced. This is mentioned here: https://github.com/catppuccin/tmux?tab=readme-ov-file#upgrading-from-v030

If you would like advice on rewriting to use the new version, this can be converted to a discussion

**Comment by rbhanot4739** [comment]
@kjnsn Yes that should be fine, lets move it to a discussion.

**Comment by rbhanot4739** [comment]
@kjnsn Can you move this to discussion or advise on how to rewrite this module ?

**Comment by kjnsn** [comment]
Don't use `-F` when setting `set -agF status-right "#{E:@catppuccin_status_pane_sync_status}"`, as this will expand too much and your text will be static.

Additionally it looks like you are never sourcing the catppuccin plugin? You need to source the plugin, and then set these options.

**Comment by rbhanot4739** [comment]
@kjnsn thanks for the response. Well,  after removing `-F` the text seems to change, but the component style isn't being applied.

```
set -g @plugin 'catppuccin/tmux#v1.0.1

# add a custom to right status to indicate if panes are pane_synchronized
%hidden MODULE_NAME="pane_sync_status"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "  "
set -ogq "@catppuccin_${MODULE_NAME}_color" "##{?pane_synchronized,#{E:@thm_red},#{E:@thm_green}}"
set -ogq "@catppuccin_${MODULE_NAME}_text" "#{?pane_synchronized,SYNC On,SYNC Off}"

source -F "/Users/rbhanot/.tmux/plugins/tmux/utils/status_module.conf"

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

set -g status-left "#{E:@catppuccin_status_session}"

set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -g @catppuccin_date_time_text "%H:%M"
set -ag status-right "#{E:@catppuccin_status_pane_sync_status}"
```
This is the entire config, and since I installed via tpm, do I still explicitly need to source the plugin as recommended in the manual section even though I am not using manual installation ?

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/f08ea67f-c844-4255-b759-d75907a0e928">

**Comment by kjnsn** [comment]
Yes, like I said, the theme options are not available until you source catppuccin. 

I'm not sure what's confusing. 

Closing as this is not an issue with the plugin

**Comment by rbhanot4739** [comment]
Confusing part is why plugin need to be sourced explicitly even after installing with tpm. Confusing part is that its not clear in the readme that you need to source the plugin no matter how you install it !!

**Comment by kjnsn** [comment]
Custom plugins are documented separately from the main readme. I also consider them an advanced feature. If you are unsure how tmux options work, then you will likely have a hard time writing config that uses the catppuccin module conf. 

We also provide no compatibility or release notes, as it's mostly an internal config. 

I'd recommend taking a look and understanding how the modules work as is, and reading the tmux man page

**Comment by rbhanot4739** [comment]
I did read and follow the custome modules readme but also source the module.conf and there is nothing specific documented as dependency on native tmux options. 

I am not sure as a user of this plugin and writing a simple custom module with 3 lines of code requires one to scrub the entire tmux man page unless there is something very specific you are looking for.

**Comment by kjnsn** [comment]
@thm_red is an option
