### ISSUE TITLE
Old Config in v0.3.0 works good, but the new config in readme with latest update has some issues.

### ISSUE THREAD

**Issue by MuntasirSZN** [catppuccin/tmux#368]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

In the latest one, you can see the statusline below. Unappropriate colors in the left side. And the rightest one, has english letters?
![image](https://github.com/user-attachments/assets/656f5ae5-29f7-490e-ac1e-5836864da114)
While in v0.3.0, the old readme config, it looked like this:
Appropriate colors in the left, and numbers in the rightest one.
![image](https://github.com/user-attachments/assets/0997087f-4ce3-4855-aadc-38f978505280)

### Paste your configuration.

OLD ONE:

```sh
unbind r
bind r source-file ~/.tmux.conf
set -g mouse on

set -g prefix C-b
bind C-b send-prefix
bind C-l send-keys 'C-l'

set-option -g status-position top
set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'
set -g default-terminal "screen-256color"

# Yazi
set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux#v0.3.0'

set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory user host session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_flavor 'mocha'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'

run '~/.tmux/plugins/tpm/tpm'
```

And The new one:
```sh
unbind r
bind r source-file ~/.tmux.conf
set -g mouse on

set -g prefix C-b
bind C-b send-prefix
bind C-l send-keys 'C-l'

set-option -g status-position top
set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'
set -g default-terminal "screen-256color"

# Yazi
set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

run '~/.tmux/plugins/tmux/catppuccin.tmux'

set -g status-left ""
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'

run '~/.tmux/plugins/tpm/tpm'
```

### What tmux version are you seeing the issue on?

tmux 3.5a

**Comment by dreknix** [comment]
It looks like the right side has been cut off because the length of the status bar is no longer set by the plugin.

Add the following configuration:

``` sh
set -g status-right-length 100
```

**Comment by davidfmatheson** [comment]
Your old look is pretty similar to mine. You can see what changes I had to make [here](https://github.com/davidfmatheson/.dotfiles/pull/1/files). I think the blue on non-active windows can be restored with:

```
set -g @catppuccin_window_default_background "#{@thm_blue}"
set -g @catppuccin_window_current_background "#{@thm_peach}"
```

You can tinker with the backgrounds for windows if you don't like the shading underneath the text:

```
set -g @catppuccin_window_default_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_color "#{@thm_bg}"
```

**Comment by MuntasirSZN** [comment]
Where is the host module?????

**Comment by kjnsn** [comment]
> Where is the host module????? And, the green number one in the old is now like, ummmm, merged? Its now pink with another icon, not like the old one.

Did you set the status right length as suggested?

**Comment by MuntasirSZN** [comment]
> > Where is the host module????? And, the green number one in the old is now like, ummmm, merged? Its now pink with another icon, not like the old one.
> 
> Did you set the status right length as suggested?

Oh forgot. I am doing it.

**Comment by MuntasirSZN** [comment]
The right side problem solved.

![image](https://github.com/user-attachments/assets/7a9f8835-f3ce-47e8-abb0-9789c970f5e4)

But In the left side, the unappropriate colors that i am meaning, in the image i have three tabs open. The left side, rightest tab has orange color, the other two is gray. But in the old one, there was no gray.

**Comment by MuntasirSZN** [comment]
> Your old look is pretty similar to mine. You can see what changes I had to make [here](https://github.com/davidfmatheson/.dotfiles/pull/1/files). I think the blue on non-active windows can be restored with:
> 
> ```
> set -g @catppuccin_window_default_background "#{@thm_blue}"
> set -g @catppuccin_window_current_background "#{@thm_peach}"
> ```
> 
> You can tinker with the backgrounds for windows if you don't like the shading underneath the text:
> 
> ```
> set -g @catppuccin_window_default_color "#{@thm_surface_1}"
> set -g @catppuccin_window_current_color "#{@thm_bg}"
> ```

Oh I forgot About This. Sorry. Yeah, it now works as the old one. Thanks guys.
