### ISSUE TITLE
Sexti

### ISSUE THREAD

**Issue by rbhanot4739** [catppuccin/tmux#379]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I am using the default config 3 as mentioned in the readme

```
set -g @plugin 'catppuccin/tmux#v1.0.3'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

# Run catppuccin plugin manually or through tpm
# ...
set -g @catppuccin_host_text "#h"
set -g status-left ""
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"
```

However, the sections on the right seems to be cropped as I don't see the hostname and session components not being displayed. This is how it looks
![image](https://github.com/user-attachments/assets/1915a976-4dec-4d35-beb1-b0dab8f3956a)

The same thing happens on the left section as well; here is a small change to display directory on the left section
```
...
set -g status-justify centre
set -g status-left "#{E:@catppuccin_status_directory}"

set -g status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

```
![image](https://github.com/user-attachments/assets/c36b978d-087b-4b55-b21f-8afb3d1c9050)

This time the directory component on the left side isn't not showing the complete directory name.

### Paste your configuration.

```
set -g @plugin 'catppuccin/tmux#v1.0.3'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

set -g status-justify centre
set -g status-left "#{E:@catppuccin_status_directory}"

set -g status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

run '~/.tmux/plugins/tpm/tpm'
```

### Attach screenshots.

![image](https://github.com/user-attachments/assets/1915a976-4dec-4d35-beb1-b0dab8f3956a)

![image](https://github.com/user-attachments/assets/c36b978d-087b-4b55-b21f-8afb3d1c9050)

### What tmux version are you seeing the issue on?

tmux 3.5

**Comment by kjnsn** [comment]
Can you please change the title? I thought this was spam

See #356

**Comment by rbhanot4739** [comment]
Still having the same issue after updating to latest version
```
set -g @plugin 'catppuccin/tmux#v1.0.3'
set -g @catppuccin_flavor "macchiato"

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

set -g status-left "#{E:@catppuccin_status_directory}"
set -g @catppuccin_directory_text "#{pane_current_path}"

set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -g @catppuccin_host_text "#h"
```
Looks the directory is not getting updated as well.
![image](https://github.com/user-attachments/assets/0f8a80dd-e474-482c-bb0a-27ae3a362ab8)

**Comment by kjnsn** [comment]
As documented in the issue I linked...

`set -g status-right-length 100`

Also I've noticed that you've opened bugs in heaps of open source projects with similar "how do I" themes. It's fine if you're not sure how to do something, but that's not a bug. Usually there will be a channel to get support, usually on reddit or discord

**Comment by rbhanot4739** [comment]
Well this specific issue very much seems like a bug if it isn't documented

> Also I've noticed that you've opened bugs in heaps of open source projects with similar "how do I" themes
Can you share examples of how many _HowTos in heaps_ have you noticed ? 

Anyways !

**Comment by kjnsn** [comment]
@rbhanot4739 I'd recommend filing an issue with tmux/tmux

**Comment by vdbe** [comment]
@rbhanot4739 `set -g status-left-length 100` should fix it (don't forget to _also_ set `status-right-length`).
