### ISSUE TITLE
`status_background "none"` with `status_fill "icon"` results in broken status module background

### ISSUE THREAD

**Issue by awwpotato** [catppuccin/tmux#384]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

when using `@catppuccin_status_fill "icon"` and `@catppuccin_status_background "none"` together, the background of the status module text bg is the highlight color (should be transparent).

### Paste your configuration.

```sh
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'catppuccin/tmux#v1.0.3'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# catppuccin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g status-position top

set -as terminal-features ",alacritty*:RGB"
set -as terminal-features ",foot:RGB"
set -g mouse on
set -g default-shell /bin/zsh

# start things at 1 not 0 (easier to reach)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# shift alt + l or h switch window
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run "~/.local/share/tmux/plugins/tpm/tpm"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"
```

### Attach screenshots.

with `@catppuccin_status_background "none"`
![image](https://github.com/user-attachments/assets/11ac1be1-1771-4b0a-8d42-170d7ac0de14)
without `@catppuccin_status_background "none"`
![image](https://github.com/user-attachments/assets/b2495ef4-9d62-4d53-9f41-a797ea482d42)

### What tmux version are you seeing the issue on?

tmux 3.4

**Comment by kjnsn** [comment]
Terminals don't support transparency, can you clarify the expectation?

**Comment by awwpotato** [comment]
oops I was misremembering how it was previously (sry). I am hoping for the first pic below, but getting the second. (Second pic is same config with `set -g @catppuccin_status_background "none"` and `set -g @catppuccin_flavor "macchiato"` removed) 
![image](https://github.com/user-attachments/assets/ac2f37a1-246b-4feb-a027-4b523d8798dc)
![image](https://github.com/user-attachments/assets/1b46b552-fb00-4674-84ea-3abcc984dace)

**Comment by davidfmatheson** [comment]
Are you trying to fix the background behind the status items on the right (your original screenshots), or are you talking about the grey bar (your most recent screenshots)? I would try

```
set -g @catppuccin_status_background "default"
```

if you want the default "mantle" background from the [palette](https://catppuccin.com/palette), or you can pick your own

```
set -g @catppuccin_status_background "#{@thm_bg}"
```

which uses "base" from the palette.

**Comment by kjnsn** [comment]
Note that "status_fill" is being removed in version two for exactly this reason - it's very difficult to reason about and get correct. 

Instead there will be two settings, and icon background and text background.

**Comment by kjnsn** [comment]
`status_fill` has been removed, closing
