### ISSUE TITLE
"Migration guide" issue missing note about "@catppuccin_window_default_text" changing

### ISSUE THREAD

**Issue by koppchen** [catppuccin/tmux#404]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

The **Migration guide** #291 issue appears to be missing a note about `@catppuccin_window_default_text` changing under the **v1 -> v2** section.

It looks like that should be:
* `@catppuccin_window_default_text`  -> `@catppuccin_window_text`

This is related to the following change:
* 79284da665bf5d39d304e23df4165c8ac37f9b7a "feat!: rebalance colors, adhere to style guide & overhaul docs"

Thanks.

**Comment by kjnsn** [comment]
Thanks! Added
