### ISSUE TITLE
Status separators do not match in size

### ISSUE THREAD

**Issue by rpop0** [catppuccin/tmux#419]
### I am not requesting help with my configuration and believe something is genuinely broken.

- [X] Something is really actually broken.

### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I've just updated my config from a previous version so I pretty much chose to go with a basic setup, but for some reason the separators (Left and right) do not match and the rounded parts are smaller than the non-rounded parts.

I've also tried setting the separators with `set -ogq @catppuccin_status_left_separator ""` but these do nothing for me.

### Paste your configuration.

set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @extrakto_popup_size "50%"

unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDown1Pane select-pane\; send-keys -X clear-selection

setw -g mode-keys vi
setw -g mouse on
set -sg escape-time 10

set -g base-index 1
set -g renumber-windows on

set -g set-clipboard on
set -g status-position bottom

setw -gq utf8 on

set -g history-limit 100000

bind '_' split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind C-r source-file ~/.config/tmux/tmux.conf

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'

run ~/.config/tmux/plugins/tmux/catppuccin.tmux

set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"

set -g @yank_with_mouse off
set -g @yank_action 'copy-pipe'

bind-key g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" "lazygit"

run '~/.tmux/plugins/tpm/tpm'

### Attach screenshots.

![image](https://github.com/user-attachments/assets/163e00d1-0021-4f78-b6ad-56349e2acb0c)

### What tmux version are you seeing the issue on?

tmux 3.5a

**Comment by rpop0** [comment]
Sooo apparently this is an issue with the alacritty terminal specifically

**Comment by kjnsn** [comment]
> Sooo apparently this is an issue with the alacritty terminal specifically

Can you provide some context for others who will inevitably have the same issue?

**Comment by kjnsn** [comment]
I use alacrity as well. It is rendering the fonts correctly. You have to use a "good" font

**Comment by kjnsn** [comment]
Found https://github.com/ryanoasis/nerd-fonts/pull/1551#issuecomment-2014826184

**Comment by kjnsn** [comment]
I've done more research. If you use the "Mono" versions of the nerd fonts this should work okay. The mono versions try to ensure the powerline glyphs are drawn into the box correctly. Using a mono version makes it a bit better

**Comment by rpop0** [comment]
> I've done more research. If you use the "Mono" versions of the nerd fonts this should work okay. The mono versions try to ensure the powerline glyphs are drawn into the box correctly. Using a mono version makes it a bit better

Hm, so apparently the default font which alacritty was using didn't work properly (I noticed my nvim lualine glyphs were also broken) and switching to FiraCode Nerd Font in the config made the issue better, but for the rounded glyphs of catppuccin I can still see a small discrepancy.

Switching between FiraCode Nerd Font and FiraCode Nerd Font Mono doesn't seem to change anything, just the size of the nerd font icons.

**Comment by kjnsn** [comment]
Right want to make clear that alacritty doesn't pick a default font, it's just the default font of your system.

Kitty does some odd hacks to make things work for specific scenarios, so YMMV
