### ISSUE TITLE
set -g @catppuccin_host "on" duplicating tmux line

### ISSUE THREAD

**Issue by brucecantarim** [catppuccin/tmux#42]
Setting `set -g @catppuccin_host "on"` causes tmux line to duplicate from time to time, displacing the lines in the buffer and making it unusable.

Removing it makes tmux go back to normal.

Current theme flavor is mocha.

Environment: tmux 3.2a - Latest Ubuntu on WSL2, Windows 11.

**Comment by ercpereda** [comment]
Works ok on MacOS with the latest version of the plugin.

**Comment by connordeckers** [comment]
I've found the issue to be in the `catppuccin.tmux` file, the specific icon for the hostname throws off the tmux rendering (I suspect it's related to Nerdfonts v3; it was breaking in my Neovim as well).

https://github.com/catppuccin/tmux/blob/4e48b09a76829edc7b55fbb15467cf0411f07931/catppuccin.tmux#L112-L115

My solution at first was to replace the icon with something else, but none of them sat nicely vertically, so I just merged it into the one section:
```bash
  local show_host
  readonly show_host="#[fg=$thm_blue,bg=$thm_gray]$right_separator#[fg=$thm_bg,bg=$thm_blue] #[fg=$thm_fg,bg=$thm_gray] #(whoami)@#H "
```
![image](https://user-images.githubusercontent.com/9065239/236823490-fbc9e34e-96fa-4f79-8e74-6c108d9b5d84.png)


It would be really great if we could do a full sweep to make sure that all the icons are supported by Nerdfonts v3, but for the time being this is a half-decent work around. :)

**Comment by 89iuv** [comment]
This is an issue with the fonts. A way to override the icons has been provided with the PR: https://github.com/catppuccin/tmux/pull/46
