### ISSUE TITLE
[BUG] active window title is messed up

### ISSUE THREAD

**Issue by shadow-absorber** [catppuccin/tmux#431]
### I am not requesting help with my configuration and believe something is genuinely broken.

- [X] Something is really actually broken.

### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

the window names is all messed up and just show the hostname instead of the actual window name. 

### Paste your configuration.
```
#set true colour mode to have better colours in tmux
set-option -ga terminal-overrides ',alacritty:RGB'
#set mouse to be enabled to handle tmux with mouse
set -g mouse on

# rebind tmux prefix to ctrl + s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# set leader r to reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# leader l to clear history
bind-key L send-keys "clear" \; send-keys "Enter"
bind-key K clear-history

# set options to make yazi work in tmux
set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'catppuccin/tmux'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -ogq @catppuccin_window_text " #W"
set -ogq @catppuccin_window_number "#I"
set -ogq @catppuccin_window_current_text " #T"
set -ogq @catppuccin_window_current_number "#I"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux

set -g status-position top

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @continuum-restore 'on'
set -g @resurrect-processes 'btop'
set -g @resurrect-capture-pane-contents 'on'

set -g @sessionx-zoxide-mode 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.config/tmux/tpm/tpm
```

### Attach screenshots.

![image](https://github.com/user-attachments/assets/b3b7ab99-d60e-4d0f-ae5a-cbfaf0c598db)

### What tmux version are you seeing the issue on?

tmux 3.5a

**Comment by shadow-absorber** [comment]
![image](https://github.com/user-attachments/assets/6279198d-a8d7-4965-a2cc-99dad0134c35)

**Comment by shadow-absorber** [comment]
the second picture shows what the blank window is supposed to be named and show

**Comment by shadow-absorber** [comment]
never mind.... changing the settings a bit seem to fix it:
```
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "
```

**Comment by aarongorka** [comment]
Best of both words if you want dynamic names by default, but still be able to override it to something meaningful:

```
set -g @catppuccin_window_text "#{?#{!=:#W,fish},#W,#T}"
set -g @catppuccin_window_current_text "#{?#{!=:#W,fish},#W,#T}"
```

(replace "fish" with whatever your windows are called by default)

**Comment by Kyren223** [comment]
+1 to this, I was confused for weeks why my windows were always my hostname, even though I explicitly gave them a name (using a script), today I was changing my tmux config, and discovered that this was only happening when using the catppuccin theme, which was very confusing, so I searched for a while and found this issue.

This is very unintuitive and bad user experience, this should not be the default.

**Comment by igops** [comment]
> never mind.... changing the settings a bit seem to fix it:
> 
> ```
> set -g @catppuccin_window_text " #W "
> set -g @catppuccin_window_current_text " #W "
> ```

@shadow-absorber a frustrating fact is that for me it works only if you source tmux config after the session starts :(
Better then nothing in any case.

**Comment by Jikeh** [comment]
> > never mind.... changing the settings a bit seem to fix it:
> > ```
> > set -g @catppuccin_window_text " #W "
> > set -g @catppuccin_window_current_text " #W "
> > ```
> 
> [@shadow-absorber](https://github.com/shadow-absorber) a frustrating fact is that for me it works only if I `source ~/.tmux.conf` after the session starts :( Better then nothing in any case.

Sharing in case it might be useful to others having the same problem, you can add a reload after the session starts with 
`set-hook -g after-new-session "source-file ~/.tmux.conf"`
