### ISSUE TITLE
Wrong behavior on status bar with separator

### ISSUE THREAD

**Issue by andreacoi** [catppuccin/tmux#435]
Catppuccin behaves unusually with the status_bar separators (right). Specifically, next to each module, a semi-circular white separator appears before the next module. Personally, I was able to fix it by modifying line 44 in utils/status_module.conf, removing #{@catppuccin_status_right_separator} and replacing it with a 'space'. I’ve attached a screenshot.

```Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_user}"
set -agF status-right "#{E:@catppuccin_status_host}"
set -agF status-right "#{E:@catppuccin_status_date_time}"
```
### Attach screenshots.

![tmux](https://github.com/user-attachments/assets/e36ee756-b078-46d9-bc72-7b3417bb77b6)

### What tmux version are you seeing the issue on?

tmux 3.3a

**Comment by kjnsn** [comment]
Can you confirm what terminal you are using, and if there is anything else in your tmux config file?

**Comment by andreacoi** [comment]
Regarding the configuration of Catppuccin, yes, I confirm that the rules present in the configuration are only these.
As for the terminal, I use Kitty.

**Comment by kjnsn** [comment]
Ah I thought it might be kitty. I'd recommend asking over on kitty for how to fix this, it's quite likely it's getting mixed up with fonts and how to display them.
