### ISSUE TITLE
Should this plugin work when using gnome-terminal or xterm?

### ISSUE THREAD

**Issue by cheyrn** [catppuccin/tmux#44]
I've installed via tpm and see no change in gnome-terminal or xterm. I'm using ubuntu in wsl2.

I can use catppuccin/gnome-terminal, but I would like to use other plugins that affect color in a terminal. Is there a way to make it work?

**Comment by Sacro** [comment]
Have you launched tmux?

**Comment by cheyrn** [comment]
On 6/17/2023 3:25 AM, Ben Woodward wrote:
>
> Have you launched tmux?
>
Yes.

show-options -g @catppuccin_flavour

results in

@catppuccin_flavour mocha

**Comment by 89iuv** [comment]
I am not sure i understand the question. 

This is a theme for tmux so as long as tmux works and can display the colors correctly then this theme should also work.
I am using this theme in wsl2 with windows terminal and i can confirm that it works.

Can you add more details to the issue?
