### ISSUE TITLE
Change window-status-format to correctly display window name

### ISSUE THREAD

**Issue by dfherr** [catppuccin/tmux#441]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

The `catppuccin_options_tmux.conf` currently sets:

```
et -ogq @catppuccin_window_text " #T"
set -ogq @catppuccin_window_number "#I"
set -ogq @catppuccin_window_current_text " #T"
set -ogq @catppuccin_window_current_number "#I"
```

this is a really weird default since it sets every single window name to the hostname and renaming your windows does not get reflected. the only useful remaining information is the window number.

I suggest changing both text values to `#W` to correctly display the window name and let users rename their windows in the status bar as expected.

**Comment by kjnsn** [comment]
Why do you believe that `#T` is the hostname? The [tmux manual](https://man7.org/linux/man-pages/man1/tmux.1.html#FORMATS) very clearly states that `#T` is the name of the pane, which can be set by the application, and that `#H` is the hostname. 

Closing for the following reasons:
1. The premise is incorrect, the default is `#T` not `#H`.
2. This is trivial to change in configuration, and how to do so is documented.
3. Using `#T` was a deliberate choice, as it means applications running inside the pane can set the title, allowing for more advanced functionality.

**Comment by dfherr** [comment]
I believe(d) it's the hostname since it was the hostname on both systems I ran the tmux server (completely seperate systems btw. a ubuntu22 workstation local install and a Rocky 9.1 server installation with their own local tmux installations).

That #T shouldn't be the hostname, I agree, but it *does* show the hostname. Why it shows that I don't know. But the user experience is the following: 

1. You install the catppuccin tmux theme
2. You reload the tmux config and see your window titles being replaced by hostnames
3. You can no longer change your window titles on the status bar (i.e. ctrl+b , updating the name is not reflected on the status bar).
4. Looking through the catppuccin tmux repository you find no reference to where the hostname is coming from (i.e. #H is only used in the host application, where it is ok. yes that's the first debugging step I did).

I agree that it can be changed through configuration. Not so much on the trivial part since the only documentation on this is that the option exists (https://github.com/catppuccin/tmux/blob/main/docs/reference/configuration.md) but I need to know which option I need to change.

My suggestion is picking a more intuitive default (i.e. one that reflects changing the window title in the window-status-text). 

To your point 1 of closing: I never made that premise. I even cited the code place that needs to be updated and currently reads #T.

Maybe it's also just me, but your response felt quite hostile to a genuine bad user experience and proposed fix. I spent 2 hours today tracking this down since I had no clue that this was the correct option to change and my window status text no longer reflected changes to my window names, but the name it showed (the hostname) was nowhere configured.

**Comment by dfherr** [comment]
To add to this: Whatever makes this work for you is likely an additional application you installed that leverages #T to be replaced by something more useful than the hostname. Unfortunately, it breaks default tmux workflows when not having additional applications controlling #T.

I hope you reconsider in the interest of your new users.

**Comment by euroclydon37** [comment]
I ran into this as well. Super new to tmux. Haven't set _any_ settings concerning this, but out of the box, window names are not updated in the status bar.

**Comment by hnbnh** [comment]
I got the same issue on mac as well, here's my spec:

- macOS Sequoia 15.2
- tmux 3.5a

**Comment by julek-wolfssl** [comment]
For future reference, place this after the `run` call that initializes your plugins (if using tpm/tpack)
```
# See https://github.com/catppuccin/tmux/issues/441
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
run ~/.tmux/plugins/tmux/catppuccin.tmux
```
