### ISSUE TITLE
strange @catppuccin_window_text behavior

### ISSUE THREAD

**Issue by 64rl0** [catppuccin/tmux#445]
### I am not requesting help with my configuration and believe something is genuinely broken.

- [X] Something is really actually broken.

### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

if I `set set-option -g @catppuccin_window_text "#[bg=default] #{?#{!=:#{window_name},},#W,} "` and for example run `vim tmux.conf` the name of the window only shows `vim` and not the full command like in the screen here. any idea why?

### Paste your configuration.

set set-option -g @catppuccin_window_text "#[bg=default] #{?#{!=:#{window_name},},#W,} "

### Attach screenshots.

<img width="1126" alt="2024-12-07_21-28-22" src="https://github.com/user-attachments/assets/b454e12f-7f54-41ea-a5c0-0c27a649dad6">

### What tmux version are you seeing the issue on?

tmux 3.5a

**Comment by kjnsn** [comment]
This is the difference between `#W` and `#T`. If you use `#T` instead, does it work as you expect?

**Comment by 64rl0** [comment]
`#T` shows the hostname of my laptop

**Comment by kjnsn** [comment]
Got it. This is an issue with whatever program you are running inside of tmux, rather than an issue with the theme or with tmux itself. Closing 

Whatever program you are running needs to set the title itself.

**Comment by 64rl0** [comment]
I have tested it on 3 devices, 2 cloud instances and my local macbook and the result is always the same. I'm running the latest version of tmux on all of the devices and using zsh. I tried many commands and nothing changes the name of the window, is there any option I need to enable in tmux?

**Comment by euroclydon37** [comment]
This is exactly what I'm running into. I've tried all the various settings suggested in the few threads that are reporting this behavior and none of them work.

**Comment by meras** [comment]
> Got it. This is an issue with whatever program you are running inside of tmux, rather than an issue with the theme or with tmux itself. Closing
> 
> Whatever program you are running needs to set the title itself.

According to the [tmux man page](https://github.com/tmux/tmux/blob/00894d188d2a60767a80ae749e7c3fc810fca8cd/tmux.1#L6314), `#T` defaults to hostname when a pane is created.

I've seen a few issues here reported with people being confused why they've hostname for pane titles and being unable to rename them.

**Comment by phamngocquy** [comment]
set -g @catppuccin_window_text " #{b:pane_current_path}" -> showing folder for window name
it's work on mac m3 pro
