### ISSUE TITLE
Status line not displaying correctly on fresh install.

### ISSUE THREAD

**Issue by glennmca-dev** [catppuccin/tmux#449]
### I am not requesting help with my configuration and believe something is genuinely broken.

- [X] Something is really actually broken.

### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

The status bar, after a fresh install, appears to have inherited the catppuccin colour scheme, but the icons, shapes etc do not change, the bar looks exactly like the standard tmux bar, with different colours.
The plugin does install correctly with no errors, but it appears it doesn't respect the config.
I receive no errors from tmux so i'm not sure what to do, i've commented out nearly everything else in my config and cannot get it to work.

### Paste your configuration.

```conf
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix
# set -g prefix C-Space
# bind C-Space send-prefix
set-option -g mouse on
set -g default-terminal "xterm-256color"
set-option -g default-shell $SHELL
set-option -g status-position top
# don't rename windows automatically
set-option -g allow-rename off
set-option -g history-limit 100000
# Make normal ctrl/alt modifiers work
set-window-option -g xterm-keys on
# bell management
set-option -g visual-bell off
set-option -g bell-action current
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'nhdaly/tmux-better-mouse-mode'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-copycat'
# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin '27medkamal/tmux-session-wizard' # <prefix> T to open a pop up for switching/creating sessions
# set -g @plugin 'kenos1/tmux-cht-sh' # <prefix> S to open a cheat sheet query
# set -g @plugin 'yardnsm/tmux-1password'
# set -g @plugin 'tmux-plugins/tmux-cpu' # Displays CPU/RAM usage in status bar
set -g @plugin 'catppuccin/tmux' # main branch
# ...alongside
# set -g @plugin 'tmux-plugins/tpm'
# set -g @catppuccin_window_current_fill "all"
# set -g @catppuccin_window_default_text "#W"
# set -g @catppuccin_window_current_text "#W"
# set -g @catppuccin_window_status_enable "yes"
# set -g @catppuccin_window_left_separator "█"
# set -g @catppuccin_window_right_separator "█"
# set -g @catppuccin_window_middle_separator " "
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_status_justify "left"
# set -g @catppuccin_status_modules_right "directory cpu date_time"
# set -g @catppuccin_status_modules_left "session"
# set -g @catppuccin_status_left_separator  ""
# set -g @catppuccin_status_right_separator " "
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_fill "all"
# set -g @catppuccin_status_connect_separator "yes"
# set -g @catppuccin_directory_text "#{b:pane_current_path}"
# set -g @catppuccin_date_time_text "%l:%M%p"
# set -g @catppuccin_cpu_text "CPU #{cpu_icon}#{cpu_percentage}|MEM #{ram_icon} #{ram_percentage}"
# # Other examples:
# # set -g @plugin 'github_username/plugin_name'
# # set -g @plugin 'github_username/plugin_name#branch'
# # set -g @plugin 'git@github.com:user/plugin'
# # set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @catppuccin_flavour 'macchiato' # latte,frappe, macchiato or mocha
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Showing wezterm conf just to show i am using a nerdfont:
```conf
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
-- config.color_scheme = 'Catppuccin Mocha'
config.color_scheme = "Catppuccin Macchiato"
-- config.color_scheme = 'Catppuccin Frappe'
-- config.color_scheme = 'Catppuccin Latte'
config.font = wezterm.font("JetBrainsMono Nerd Font")
config.font_size = 13.0

local act = wezterm.action
-- Set "Natural text editing" keys (mac os default)
config.keys = {
	{ mods = "ALT", key = "LeftArrow", action = act.SendKey({ mods = "ALT", key = "b" }) },
	{ mods = "ALT", key = "RightArrow", action = act.SendKey({ mods = "ALT", key = "f" }) },
	{ mods = "CTRL", key = "LeftArrow", action = act.SendKey({ mods = "CTRL", key = "a" }) },
	{ mods = "CTRL", key = "RightArrow", action = act.SendKey({ mods = "CTRL", key = "e" }) },
	{ mods = "CTRL", key = "Backspace", action = act.SendKey({ mods = "CTRL", key = "u" }) },
}
-- disable tab bar
config.enable_tab_bar = false

-- and finally, return the configuration to wezterm
return config
```

### Attach screenshots.

![Screenshot from 2024-12-23 00-38-22](https://github.com/user-attachments/assets/e32ce4c8-1c6c-4bdc-b5d8-6e4efd735713)

### What tmux version are you seeing the issue on?

tmux 3.4

### Any additional comments?

I should note this issue is happening on my linux mint 22 pc, i use the same config (without everything commented out) with tmux 3.3a on my macbook and it works as expected. so i'm not sure what the issue is.

**Comment by glennmca-dev** [comment]
I don't understand how this solves the issue? you've just told me not to use TPM (i	assume you didn't look at my config closely). providing i don't install any other plugins called `tmux` then TPM should work fine. The issue i'm having seems to be that the config is not being respected by the plugin. 
I have custom shapes and extra plugins for the left and right side of the catppuccin status bar, they aren't appearing as expected, but work fine on my mac os work computer. I still believe there is a problem here.

**Comment by glennmca-dev** [comment]
If this is a configuration issue, is there a recommended forum i should go to, to discuss this with other users?

**Comment by glennmca-dev** [comment]
Okay, so from looking at the docs it seems the names of the available config options and the rules around them have changed, hence my config not being respected because it's no longer valid. I'm obviously using a much older version of this plugin on my work laptop.
For anyone else running into this issue, have a look at https://github.com/catppuccin/tmux/blob/main/docs/reference/configuration.md

**Comment by kjnsn** [comment]
> If this is a configuration issue, is there a recommended forum i should go to, to discuss this with other users?

Feel free to start a discussion in https://github.com/catppuccin/tmux/discussions
