### ISSUE TITLE
Time module icon display error after update nerdfont 

### ISSUE THREAD

**Issue by kola-web** [catppuccin/tmux#48]
![image](https://github.com/catppuccin/tmux/assets/46446884/a751adf8-dc9d-40ca-bc8f-04880efadd03)

**Comment by LeBaronDeCharlus** [comment]
Same here :

```
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_flavour 'latte'
set -g @catppuccin_date_time "%Y-%m-%d %H:%M"
set -g @catppuccin_window_tabs_enabled on
set -g @catppuccin_left_separator "█"
set -g @catppuccin_right_separator "█"
```

**Comment by kfnx** [comment]
its showing for me after I install nerdfont and set the font to it on wsl appearance config

**Comment by bassamsdata** [comment]
It's working on kitty but it doesn't work on Alacritty despite using the same nerd font JetBrainsMono Nerd Font

**Comment by Stianhn** [comment]
This PR should fix it. https://github.com/catppuccin/tmux/pull/45

**Comment by adikari** [comment]
I am having the same issue. overwriting the icon is not working either. Here is the screenshot

![image](https://github.com/catppuccin/tmux/assets/1757714/0caf1f14-c190-4e74-93a8-d064536244e2)

**Comment by 89iuv** [comment]
This is an issue with the fonts. A way to override the icons has been provided with the PR: https://github.com/catppuccin/tmux/pull/46
