### ISSUE TITLE
Tmux window names are not respected

### ISSUE THREAD

**Issue by aimestereo** [catppuccin/tmux#53]
Notes: 
* I have latest version installed via TPM.
* I don't know if this behaviour by design, but at least it smth that should be configurable.

### Issue

If I rename window (or even pane), names in the bottom shows smth different (current folder?). 
For now I'm using this version that doesn't have this issue: https://github.com/dreamsofcode-io/catppuccin-tmux/commit/b4e0715356f820fc72ea8e8baf34f0f60e891718
Regretfully I can't be more useful, I don't even know if this version fixes smth, or if there's a bug in latest commits in main repo (https://github.com/dreamsofcode-io/catppuccin-tmux is quite behind main repo)

### Examples

<details>
  <summary>pic 1: main - wrong window names</summary>

  ![Screenshot 2023-07-09 at 12 23 22](https://github.com/catppuccin/tmux/assets/2869535/a06e7d21-cb3d-4347-89bd-1e8b2778eaf4)
</details>

<details>
  <summary>pic 2: alternative - window names are respected, if not set, shows current program name</summary>

  ![Screenshot 2023-07-09 at 12 24 40](https://github.com/catppuccin/tmux/assets/2869535/a3e629b3-2b3a-410f-92a1-6d23232bc28a)
</details>

---

### Additional info

My config, only relevant part:

```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'dreamsofcode-io/catppuccin-tmux'  # catppuccin with more info in bottom line
set -g @plugin 'catppuccin/tmux'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

My whole config
```
set -s mouse on

unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Start windows and panes # with 1 (not 0), and renumber on close.
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# set vi mode for selection and copy
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"


# Shift Alt vim keys to switch windows.
bind -n M-H previous-window
bind -n M-L next-window

# Custom keys for splits + Open splits in the same directory
bind 's' split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"


#
# List of plugins
#
# prefix + I - to [I]nstall plugins
# prefix + U - to [U]pdate plugins
# prefix + alt + u - to [U]ninstall plugins that are not in the list
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'  # catppuccin with more info in bottom line
#set -g @plugin 'catppuccin/tmux'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'



#
# Complex configs
#

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'M-h' select-pane -L
bind-key -T copy-mode-vi 'M-j' select-pane -D
bind-key -T copy-mode-vi 'M-k' select-pane -U
bind-key -T copy-mode-vi 'M-l' select-pane -R
bind-key -T copy-mode-vi 'M-\' select-pane -l


```

**Comment by dipta10** [comment]
Does this help?
```
set -g @catppuccin_window_tabs_enabled off
```

**Comment by dipta10** [comment]
Does this help?
```
set -g @catppuccin_window_tabs_enabled on
```

**Comment by 89iuv** [comment]
It looks like catppuccin is not configured to show the name of a window when it has been renamed. 
I am looking into a fix to override the window name when a user manually sets the name.

**Comment by 89iuv** [comment]
With the new settings you need to use the following:
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

This will set the status bar window to display the window name.

**Comment by aimestereo** [comment]
@89iuv works, thanks

**Comment by zezking** [comment]
If want the window name to displayed event when it's not selected. The above configs only display window name when a window is selected.
Add the following line along with the above:
set -g @catppuccin_window_text "#W"

**Comment by andreabertanzon** [comment]
> The above configs only display window name in when a window is selected for me. If you want the window name to displayed by default. Add the following line along with the configs provided by @89iuv set -g @catppuccin_window_text "#W"

You're my hero!

**Comment by jnussbaum** [comment]
> > The above configs only display window name in when a window is selected for me. If you want the window name to displayed by default. Add the following line along with the configs provided by [@89iuv](https://github.com/89iuv) set -g @catppuccin_window_text "#W"
> 
> You're my hero!

And my hero, too!

I think this should actually be added to the recommended default configuration. IMHO, these 2 pages are not accurate, and should be updated:

- https://github.com/catppuccin/tmux/tree/main?tab=readme-ov-file#recommended-default-configuration
- https://github.com/catppuccin/tmux/blob/main/docs/tutorials/01-getting-started.md#step-3-customize

I'd be happy to open a PR, what do you think, @89iuv ?

**Comment by kjnsn** [comment]
Happy to accept a PR to change the default config in the readme and the customisation page

**Comment by jnussbaum** [comment]
> Happy to accept a PR to change the default config in the readme and the customisation page

Thanks for your prompt response. The PR is ready here: https://github.com/catppuccin/tmux/pull/472

**Comment by Islamsulaiman** [comment]
> The above configs only display window name when a window is selected for me. If you want the window name to displayed by default, add the following line along with the configs provided by [@89iuv](https://github.com/89iuv) set -g @catppuccin_window_text "#W"

Thanks, this is what worked for me as well.

**Comment by AnthonyDelaCruz** [comment]
> The above configs only display window name when a window is selected for me. If you want the window name to displayed by default, add the following line along with the configs provided by [@89iuv](https://github.com/89iuv) set -g @catppuccin_window_text "#W"

New tmux explorer here, this worked for me as well! I hope they add this caveat in the documentation, took me a while to find why the rename didn't work, I knew it had something to do with catppuccin since it worked before I installed it but I didn't know how it affected it.

**Comment by natskis** [comment]
> None of the above worked for me. I found a solution though. Add these lines to your `.tmux.conf`, above where you load catppuccin.
> 
> ```
> set -ogq @catppuccin_window_text " #W"
> set -ogq @catppuccin_window_current_text " #W"
> 
> ...
> set -g default-terminal "tmux-256color"
> set -g @catppuccin_flavor "mocha"
> run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
> ```

This fixed my issue! Banging my head against a brick wall for AGES on this one! 
Thank you !!!!!
