### ISSUE TITLE
Rounded pills option showing improperly

### ISSUE THREAD

**Issue by win20** [catppuccin/tmux#55]
When I add `set -g @catppuccin_pill_theme_enabled on`, it appears like this:
![Screenshot from 2023-07-15 16-14-01](https://github.com/catppuccin/tmux/assets/22985058/1d0b3c75-ab44-44e8-958a-80cbab56af8c)

As you can see it's only done the rounded pills on the right side and they also show up jagged almost like it's added the pills on top of existing non patched components.

I'm on Ubuntu using Alacritty.

**Comment by VeejayPL** [comment]
This is a default behaviour.
To have the pill theme on the left side as well, you need to enable window tabs option:  `set -g @catppuccin_window_tabs_enabled on`

For the icons not showing properly, you probably need to play with the Alacritty settings: font size, line height etc. Or Google up Nerd fonts on Alacritty. 

In worst case scenario, you can always configure your own icons for left and right separator. For that please refer to configuration options.
