### ISSUE TITLE
Window right separator not reflected in layout

### ISSUE THREAD

**Issue by b4rlw** [catppuccin/tmux#66]
No space is present when using:
```
set -g @catppuccin_window_right_separator "█ "
```
or
```
set -g @catppuccin_window_right_separator " "
```

It *is* present when using the left variant though.

Thanks for the reworked plugin!

**Comment by 89iuv** [comment]
It looks like somewhere the string gets striped of all trailing white spaces.
A workaround is to use a no-break unicode character:
https://www.compart.com/en/unicode/U+00A0#:~:text=“%20”%20U%2B00A0%20No%2D,Break%20Space%20(NBSP)%20Unicode%20Character
