### ISSUE TITLE
Add 'last right seperator'

### ISSUE THREAD

**Issue by assignUser** [catppuccin/tmux#67]
Hey thanks again for the plugin! 

Not sure if it is clear what I mean with the title so let me add an image:
![image](https://github.com/catppuccin/tmux/assets/16141871/d0bf0643-ddcc-490f-9bbb-255cf58f867f)
It would be great if I could match the tmux status line to my p10k prompt. I have removed the space but what I am looking for is a way to set the last right seperator to flat as seen in the zsh prompt. 

As far as I could see this is not possible at the moment? Or are there module specific overrides?

**Comment by 89iuv** [comment]
I did a refactor which enables to do what you want.
Update the plugin and use the following config as an example:
```bash
set -g @catppuccin_status_modules "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "yes"
```

<img width="374" alt="image" src="https://github.com/catppuccin/tmux/assets/3298487/fe5f5d35-300e-407d-981e-ddb3f0fc563d">

**Comment by assignUser** [comment]
Amazing! Works perfectly, thank you!
