### ISSUE TITLE
Error upon running `tmux source-file ~/.tmux.conf`

### ISSUE THREAD

**Issue by lokka30** [catppuccin/tmux#7]
Hi, thank you for this theme!

There seems to be an error somewhere in the file, as I receive this output upon running `tmux source-file ~/.tmux.conf`:

```
bad style: fg=#c2e7f0,bg=#332e41,align=centre
bad style: fg=#c2e7f0,bg=#332e41,align=centre
```

**Comment by nekowinston** [comment]
Closing this since the theme got updated to Catppuccin v0.2.0 with https://github.com/catppuccin/tmux/commit/49845e02b38c5070e95bf4083feaf886940db68b, please open a new issue, should a similar problem persist.
