### ISSUE TITLE
More configuration options

### ISSUE THREAD

**Issue by ervinpopescu** [catppuccin/tmux#77]
I would like to have this in the repo as well:
```tmux
set -g @catppuccin_window_left_separator_inverse "yes"
set -g @catppuccin_window_right_separator_inverse "yes"
set -g @catppuccin_status_left_separator_inverse "yes"
```
I'm going to try to add it myself and make a PR, but I don't have a lot of free time, so it's going to take a while. If you guys think you can do it faster, please go ahead.

LE: 

```tmux
set -g @catppuccin_window_connect_separator "yes"
```
would be nice too.

**Comment by 89iuv** [comment]
I like the idea but i also do not have a lot of free time. I can help with the PR if you manage to find the time to do it.

**Comment by ervinpopescu** [comment]
Any objections against `shfmt`? I'm using it in neovim and it formatted the whole `catpuccin.tmux`...

**Comment by kjnsn** [comment]
This is trivial, just use `#[reverse]`

**Comment by ervinpopescu** [comment]
> This is trivial, just use `#[reverse]`

Could you give an example of that?

**Comment by ervinpopescu** [comment]
Found answer in https://github.com/catppuccin/tmux/tree/main/docs/tutorials/02-custom-status.md.
