### ISSUE TITLE
Icons render with sigma sign?

### ISSUE THREAD

**Issue by gusseleet** [catppuccin/tmux#79]
I have the `Jetbrains Mono` font installed. But for some reason it looks like this?

![image](https://github.com/catppuccin/tmux/assets/15208564/48bc20f0-d4a0-4ae5-b660-f3ee819c43b1)

Any clue whats going on?

**Comment by 89iuv** [comment]
This looks to be a font issue. Try it with the jetbrains mono patched font from nerdfont: https://www.nerdfonts.com/font-downloads

**Comment by gusseleet** [comment]
But I have installed it, and `fc-list` shows all the installed fonts from `JetbrainsMono`. I have this one installed:

https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip

Because the icons from the font shows (ie the terminal and the human). But something is weird with them indeed.

**Comment by gusseleet** [comment]
Sorry, was not suppose to close the issue.

**Comment by 89iuv** [comment]
You could try using vim and pasting the icons in a text file. It should render the icons correctly. 
It could also be a terminal issue.

**Comment by faiz-crypto** [comment]
I have a similar issue. I also have installed Fira Code and its added to the terminal and tmux as far as I can see. I have tested that fonts work independently in the terminal. This is on Ubuntu 20.04 if that helps.

**Comment by 89iuv** [comment]
@faiz-crypto can you please give me the link from where you installed the font?

**Comment by faiz-crypto** [comment]
@89iuv I did a `sudo apt install fonts-firacode`

**Comment by faiz-crypto** [comment]
@89iuv that did work for me. Thanks.
