### ISSUE TITLE
Background color for default vs current window

### ISSUE THREAD

**Issue by bendavis78** [catppuccin/tmux#80]
I find the background color for the default vs current window a bit confusing. It seems that the current window should have the lighter bg, while the default should have the same bg as the whole line. Instead it's inversed, so if two windows are opened it looks like the non-current window is current.

**Comment by 89iuv** [comment]
Indeed it was confusing for me at first. I did not want to mess with the original vision of the author and change the default.
The solution here would be to make the background configurable for default and current window.

**Comment by formigarafa** [comment]
I had the same initial feeling but, wondered about configuration options too.
but to be honest, I think it had been a mistake to set the active window to be the same as bg color. It just doesn't make sense. 
Even your separator icons won't appear if you do so. 
Why would one go to the lengths to make the icons configurable if they are not visible?
<img width="378" alt="image" src="https://github.com/catppuccin/tmux/assets/160616/da1b539f-25ba-47b8-b9a0-243df46f06b5">

I am no specialist here but just gave a bash to change `background` from `$thm_bg` to `$thm_black4` which they provide and the stars seem to align for me:
<img width="355" alt="image" src="https://github.com/catppuccin/tmux/assets/160616/89078ebe-e7ae-4ad6-8911-8583bf9e3786">

**Comment by sgoudham** [comment]
Closing as https://github.com/catppuccin/tmux/pull/94 was merged, making this user configurable.
