### ISSUE TITLE
Example configurations issue: separators always have wrong color

### ISSUE THREAD

**Issue by juk0de** [catppuccin/tmux#81]
Hi!

 I'm trying to get the configuration examples working (especially the [first one](https://github.com/catppuccin/tmux#config-1)), but without success. The status area looks fine, but the window area does not:

![tmux](https://github.com/catppuccin/tmux/assets/5322305/e1bcaab0-59b2-4c5f-90ac-a5af52e04708)

As you can see, the separators are colored, unlike in the [example screenshot](https://github.com/catppuccin/tmux#config-1). No matter which theme I set, those huge blue separators remain. Here's my current configuration:
```
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_modules_right "application host user session"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-processes 'ssh "sudo su"'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'
```
And yes, I did `tmux kill-server` and I also tried it an different machine, but the issue remains.

Do you have any suggestions on how to fix this?

**Comment by ProgrammingFire** [comment]
I am also facing the same issue!

**Comment by AlexNabokikh** [comment]
@89iuv @ervinpopescu 
#78 breaks existing configs

**Comment by shubhisroking** [comment]
![2023-09-11_17-06](https://github.com/catppuccin/tmux/assets/138035866/d9ce6a39-16ed-4db4-b223-a5b21c7a7807)
was about to make a issue about

**Comment by 89iuv** [comment]
Reverted the PR https://github.com/catppuccin/tmux/pull/78.

**Comment by shubhisroking** [comment]
> Reverted the PR #78.

fixed, ig we can close this issue now

**Comment by ervinpopescu** [comment]
My bad, please try out the PR #82 and tell me if that fixes it.
@juk0de @ProgrammingFire @shubhisroking

**Comment by juk0de** [comment]
Didn't you test the default configurations with your PR @ervinpopescu? That would the obvious thing to do imho...

**Comment by ervinpopescu** [comment]
> Didn't you test the example configurations with your PR @ervinpopescu? That would the obvious thing to do imho...

Of course I did, but if you would like to test some more, go ahead.
