### ISSUE TITLE
changing theme flavour for a running server does not work

### ISSUE THREAD

**Issue by nimaai** [catppuccin/tmux#83]
Hi 

I like to change my iterm & tmux & vim themes from light to dark and vice-versa throughout the day.

My workflow is as follows:
1. I detach the tmux session.
2. I change the flavour in iterm.
3. I change the flavour for tmux from terminal: `tmux set-option -g @catppuccin_flavour ...`.
4. I attach the tmux session.

I have also tried to source the `.tmux.conf` file as well as reload the `tpm` after 3. but it doesn't work. This workflow of mine was working with the solarized theme.

What am I missing here?

Thanks for help.

**Comment by nimaai** [comment]
`tmux run-shell '~/.tmux/plugins/tpm/tpm'` after 3. does the job. I was messing up something before.

**Comment by nimaai** [comment]
it stopped working after i have upgraded to the latest version. i am not using `tpm` anymore. i have followed the manual setup as recommended. the plugin in itself works perfectly, but dynamically changing the flavor for running server not. what is the current way to do it?

**Comment by kjnsn** [comment]
Due to the complexity of this plugin, this cannot be easily supported. You could manually unset some of the internally derived options on reload if you really wanted

**Comment by milch** [comment]
I had the same workflow as well, which was working fine on <0.2.0 but is broken starting on 1.0.0. To reproduce, tmux.conf:

```
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

run ~/.config/tmux/plugins/tmux/catppuccin.tmux
```

- Reload the server
- Prefix+: `set -g @catppuccin-flavor 'latte'`
- Prefix+: `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`
- Nothing changes 

Considering there seems to be some interest in this feature from @nimaai as well as other users that asked about setting up automatic theme changes in the past, would you reconsider marking this as not planned?

**Comment by kjnsn** [comment]
I'm really hesitant to build this into the theme the way that it works. Switching the colours on a tmux _server_ based on what is happening on a _client_ seems like an antipattern. Tmux is quite strict w.r.t. the client-server model, and works well when that model is followed.

Therefore, I'd highly recommend using colours that rely on the terminal itself. See the `terminal` style here: https://man7.org/linux/man-pages/man1/tmux.1.html#STYLES

If your terminal is using the catppuccin colours then you don't really need to style tmux at all, just make tmux style things _less_
