### ISSUE TITLE
unable to install with oh my tmux

### ISSUE THREAD

**Issue by Brian16446** [catppuccin/tmux#86]
I'm using [Oh my tmux](https://github.com/gpakosz/.tmux) and I'm adding `set -g @plugin 'catppuccin/tmux'` into my .tmux.conf.local as suggested by oh my tmux but it fails to install the plugin.

I've tested other plugins, for example [tmux powerline](https://github.com/erikw/tmux-powerline) and it installs just fine, it's just this plugin that's not working

**Comment by lakmalniranga** [comment]
Same issue here. I'm getting the below error when I reload the tmux configurations.

```
'~/.tmux/plugins/tpm/tpm' returned 1
```

**Comment by anandbibek** [comment]
Same problem here. On linux getting this error, while same thing apparently working fine on mac.

`$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm' returned 1`

**Comment by asilvam133** [comment]
I’m using Mac, and have the same error and it is the Catppuccin plugin causing it.

**Comment by anandbibek** [comment]
Apparently my errors were due to quite old tmux version. Updated to 3.3a and errors are gone.

**Comment by jfujitani** [comment]
I  had a similar issue.  I was using tmux plugin manager TPM.  I noted that I had a previous theme dracula/tmux installed.  I ended up having to deleted the  .tmux/plugins/tmux folder 
As I noticed catppuccian and dracula both used that folder.

**Comment by 89iuv** [comment]
For now [Oh my tmux](https://github.com/gpakosz/.tmux) is not supported.

**Comment by jfujitani** [comment]
> I had a similar issue. I was using tmux plugin manager TPM. I noted that I had a previous theme dracula/tmux installed. I ended up having to deleted the .tmux/plugins/tmux folder As I noticed catppuccian and dracula both used that folder.

One other thing worth checking.  Many linux package repos are way out of date with the version tmux they provide.  On few machines I had to install latest from source to get this plugin fully working.
I'm not sure if the readme.md has a minimum version listed in the dependencies but, it would certainly be helpful if not.
