### ISSUE TITLE
Problem with status bar font

### ISSUE THREAD

**Issue by faeb5** [catppuccin/tmux#9]
Hi, I'm using a Nerd Font in my terminal, so the status bar icons in tmux should be displayed properly. However, this is how it looks currently:

![20220602_13h23m44s_grim](https://user-images.githubusercontent.com/68775216/171619322-e6bdb97d-e729-4b5f-b427-cc7bb9de66ee.png)

Any idea? I'm using CascaydiaCove Nerd Font.

**Comment by faeb5** [comment]
Sorry, I realize that this issue has most likely nothing to do with the theme itself but with the configured fonts. I'll close this.

**Comment by eric-tramel** [comment]
I wish @faeb5 you had followed up with the root cause -- i.e. which font or setting had caused this. Run into the same out of the box even with proper Nerd fonts.
