### ISSUE TITLE
Improve documentation / add examples of custom modules

### ISSUE THREAD

**Issue by ixzh** [catppuccin/tmux#90]
For example, I want to show `#{forecast}` from `'aaronpowell/tmux-weather'`.

I put  `set -g @catppuccin_status_modules_right "#{forecast} application session"`. didn't seem work.

**Comment by vladimir-popov** [comment]
Maybe this readme can help https://github.com/catppuccin/tmux/blob/main/custom/README.md

**Comment by zeidlos** [comment]
Is there a possibility for any further documentation on this?
I can't get the stuff from 'custom/README' to work at all.

**Comment by 89iuv** [comment]
Paste here your module config and i can have a look over it.

**Comment by omurilo** [comment]
I use the `example`  file has on `custom` folder and my plugin doesn't load.

**Comment by Myzel394** [comment]
> In order to include another plugin, you need to write a custom module that uses that plugin.

I'm facing the same issue. I want to include a different plugin but have no idea how to properly add it. I was able to create a dummy "Hello World" module that displayed correctly, but how do I call a plugin? I'm specifically talking about adding the module https://github.com/vascomfnunes/tmux-kripto

**Comment by fazlearefin** [comment]
Thanks I was able to get what I wanted following the guidance you provided. 

For anyone trying to do the same, here is what I did:

1. Create file called `uptime.sh` in `$HOME/.tmux/plugins/tmux/custom` with contents:

```sh
# shellcheck shell=bash

show_uptime() { # This must match the module name!
  local index icon color text module

  index=$1
  icon="$(get_tmux_option "@catppuccin_test_icon" "")"
  color="$(get_tmux_option "@catppuccin_test_color" "$thm_orange")"
  text="$(get_tmux_option "@catppuccin_test_text" "#( python3 $HOME/.tmux/plugins/tmux/custom/custom_uptime.py )")"

  module=$(build_status_module "$index" "$icon" "$color" "$text")

  echo "$module"
}
```

2. Create `custom_uptime.py` in `$HOME/.tmux/plugins/tmux/custom` with contents:

```python
#!/usr/bin/env python3
import os
import time

def get_uptime():
    with open('/proc/uptime', 'r') as f:
        uptime_seconds = float(f.readline().split()[0])
        uptime_minutes = uptime_seconds // 60
        uptime_hours = uptime_minutes // 60
        uptime_days = uptime_hours // 24
        uptime_hours %= 24
        uptime_minutes %= 60
        return int(uptime_days), int(uptime_hours), int(uptime_minutes)

def get_load_average():
    return os.getloadavg()

def format_uptime(days, hours, minutes):
    if days > 0:
        return f"{days}d {hours}h {minutes}m"
    elif hours > 0:
        return f"{hours}h {minutes}m"
    else:
        return f"{minutes}m"

def main():
    uptime_days, uptime_hours, uptime_minutes = get_uptime()
    load_avg = get_load_average()
    formatted_uptime = format_uptime(uptime_days, uptime_hours, uptime_minutes)
    formatted_load_avg = [f"{avg:.1f}" for avg in load_avg]
    print(f"{formatted_uptime} | {' '.join(formatted_load_avg)}")

if __name__ == "__main__":
    main()
```

3. Include the custom module `uptime` in `$HOME/.tmux.conf`

**Comment by sgoudham** [comment]
Hey :wave: 

I'd appreciate if either @qadzek or @fazlearefin could raise a PR to the custom docs section to improve it. It's a shame for it to be buried in issues!
