### ISSUE TITLE
Username and Hostname for SSH connections

### ISSUE THREAD

**Issue by renantmagalhaes** [catppuccin/tmux#93]
Hi all,

There's an easy way to import the gpakosz module/configuration username_ssh and hostname_ssh? 

This dynamically changes the username/hostname based on the panel, even if the panel is connected with a remote host.

I have tried to build a custom module but have been unsuccessfully so far. Maybe someone already solved this issue :)

**Comment by ericpar234** [comment]
Found this plugin:
```
set -g @plugin 'soyuka/tmux-current-pane-hostname'

set -g @catppuccin_user_text "#U"

```

**Comment by 89iuv** [comment]
@renantmagalhaes did the comment from @ericpar234 helped you to fix the issue?

**Comment by renantmagalhaes** [comment]
Hey @ericpar234  and @89iuv 

Thank you for the feedback, However, I ended up moving toward my own config, so I will not be able to validate. 

Feel free to close the issue 

Thanks all!

**Comment by LiamFry** [comment]
I realized this is a closed issue and it's more than a year later ... However, I find myself in the same situation as the OP. I do *a lot* of remote stuff and it would be nice if my _catppuccin_ styling was relevant for a tmux window that held a remote (ssh) session. As it is now, each tmux window shows "application : local-user @ local-host : current-path" for everything. The window title is "stuck" at showing the local info even when I'm in a remote session.

I tried the solution offered by @ericpar234 but I have the same problem as those outlined in [soyuka/tmux-current-pane-hostname #8](https://github.com/soyuka/tmux-current-pane-hostname/issues/8) ... it simply does not work (for me); both `#H` (`#hostname`) and `#U` (`#username`) remain unset.

**Comment by AminGholizad** [comment]
I managed to make it work by adding these lines.

```
set -g @plugin "soyuka/tmux-current-pane-hostname"
...
set -g @catppuccin_host_text " ##U@##H"
...
set -agF status-right "#{E:@catppuccin_status_host}
```
## notes:
- F = (Expand/Format): This tells tmux to treat the value as a format string.
- `##H` make it so after catppuccin renders it, it is still `#H` left for soyuka to update. otherwise `#H` is rendered to hostname by catppuccin.
