### ISSUE TITLE
Theme not working on Ubuntu on WSL 2

### ISSUE THREAD

**Issue by TheGthr** [catppuccin/tmux#96]
Greetings,
I share the following `tmux.conf` on all my machines:

```bash
set -g status-interval 1
set -g escape-time 10
# Set true colors
set-option -sa terminal-overrides ",xterm*:Tc"
# Enable mouse support
set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift+Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Use Shift+Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

set -g @catppuccin_flavour 'mocha'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-catppuccin'
set -g @plugin 'tmux-plugins/tmux-yank'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

run ~/.tmux/plugins/tpm/tpm
```
I wanted to apply to my WSL 2 Ubuntu instance but I cannot make it work, the window still looks like the original tmux window (with the green bar at the bottom). And all the other plugins are working -sensible, yank...). The `tmux.conf` file is located in `~/.config/tmux/tmux.conf`.

Other information:
- Windows 11 (but also tested and not working on Win10)
- Ubuntu 23.04
- tmux 3.3a

Has someone faced this issue before?
Thanks

**Comment by hmooms** [comment]
I got it working when I changed the Catppuccin plugin to this 
```tmux
set -g @plugin 'catppuccin/tmux'
```

**Comment by TheGthr** [comment]
@hmooms I don't know why I posted `set -g @plugin 'tmux-catppuccin'`, as I do have `set -g @plugin 'catppuccin/tmux'` in my config, sorry for the typo in my original post. Therefore, your fix does not work for me, thank you anyway

**Comment by hmooms** [comment]
Have you installed it using the prefix + I (capital i)? I personally forgot that before.

**Comment by TheGthr** [comment]
Yes, I did that too, and I also sourced the `~/.conf/tmux/tmux.conf` file in tmux

**Comment by hmooms** [comment]
Last things I can think of, but I'm not sure it will make difference
```tmux
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
```
and maybe setting your flavour after the plugin, but that probably doesn't make any difference.

My setup:

- Windows 10
- Ubuntu 22.04
- tmux 3.2a
- Catppuccin terminal theme
- JetBrainsMono Nerd Font

**Comment by TheGthr** [comment]
It did not change anything for me unfortunately... Thanks!

**Comment by jamesfehrmann** [comment]
I got mine working.  I'm not sure what step did the trick, but here's what I did:

1. Download tpm into `~/.tmux/plugins/tpm`
`git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm`

2. Create `~/.config/tmux/tmux.conf` _(source below)_

3.  Load the config.
`tmux source ~/.config/tmux/tmux.conf`  and `<prefix>I` _(capital 'i')_

4. Repeat step 3 a couple times.

5. Change font in the windows terminal to a Nerd Font like "Sauce/SourceCodePro Nerd Font"
https://www.nerdfonts.com/font-downloads
https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/SourceCodePro.zip
_(For a linux desktop, you need to install the fonts in Linux.  **For WSL**, you need to install the font in Windows and use the terminal application's settings panel to set Font Face.)_

![image](https://github.com/catppuccin/tmux/assets/1512967/2ead9a44-2035-4a57-b4f6-18fea5e68f16)


Tmux Config:
```
#Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

#Turn on Mouse Support
set -g mouse on

# Start windows and panes at index 1 instead of 0
set -g base-index 1
set -g pane-base-index 1


#Set prefix key
unbind C-b
set -g prefix `

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

#Run plugin manager
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by TheGthr** [comment]
Thank you for your answer, unfortunately, it did not work for me... But I found a solution! I had my `tmux.conf` in `~/.config/tmux/tmux.conf`, and I was calling at the end of it `~/.tmux/plugins/tpm/tpm`. In fact, I had tpm installed in `~/.tmux/plugins/tpm/tpm` AND in `~/.config/tmux/plugins/tpm/tpm`. So:
- I deleted `~/.tmux`
- I added `run '~/.tmux/plugins/tpm/tpm'`

And now everything is working fine for my catppuccin theme. Thanks again for the help
