### ISSUE TITLE
Add an ability to set location of custom modules dir

### ISSUE THREAD

**Issue by aikixd** [catppuccin/tmux#99]
Currently, the `custom` dir that is used to define custom modules is located in the `<config dir>/tmux/custom`, where `tmux` is a git repo. This means that when `<config dir>` is by itself a git repo, I can't add files from the `custom` dir into the config repo, since it is in a nested repo.

A way to customize the location of the `custom` dir path should be given, so custom modules would be able to be a part of the user's tmux config.

**Comment by peterkracik** [comment]
+1

**Comment by 89iuv** [comment]
Good suggestion. I will look into it.
